specify dependency

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -25,6 +25,7 @@
 # @parseArger opt history "add n history lines at the end of the file"
 # @parseArger opt history-offset "offset --history value by value"
 # @parseArger opt history-file "specify history file" --default-value "\$HOME/.bash_history"
+# @parseArger opt dependencies "specify script dependencies" --repeat
 # @parseArger flag leftovers "accept extra arguments"
 # @parseArger flag bang "include shebang" --on
 # @parseArger flag version-opt "generate version opt handling" --on
@@ -79,6 +80,7 @@ _arg_nested=()
 _arg_history=
 _arg_history_offset=
 _arg_history_file="$HOME/.bash_history"
+_arg_dependencies=()
 # FLAGS
 _arg_leftovers="off"
 _arg_bang="on"
@@ -117,6 +119,7 @@ print_help()
 	echo -e " --history <history>: add n history lines at the end of the file"
 	echo -e " --history-offset <history-offset>: offset --history value by value"
 	echo -e " --history-file <history-file>: specify history file [default: ' \$HOME/.bash_history ']"
+	echo -e "	--dependencies <dependencies>: script dependencies, repeatable"
 	echo -e "	--leftovers|--no-leftovers: accept extra arguments"
 	echo -e "	--bang|--no-bang: include shebang, on by default (use --no-bang to turn it off)"
 	echo -e "	--version-opt|--no-version-opt: generate version opt handling, on by default (use --no-version-opt to turn it off)"
@@ -345,31 +348,39 @@ parse_commandline()
 				_arg_nested+=("${_key##--nested=}")
 				;;
 			--history)
-							test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-							_arg_history="$2"
-							shift
-							;;
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_history="$2"
+				shift
+				;;
 			--history=*)
-							_arg_history="${_key##--history=}"
-							;;
+				_arg_history="${_key##--history=}"
+				;;
 
 			--history-offset)
-							test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-							_arg_history_offset="$2"
-							shift
-							;;
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_history_offset="$2"
+				shift
+				;;
 			--history-offset=*)
-							_arg_history_offset="${_key##--history-offset=}"
-							;;
+				_arg_history_offset="${_key##--history-offset=}"
+				;;
 
 			--history-file)
-							test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-							_arg_history_file="$2"
-							shift
-							;;
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_history_file="$2"
+				shift
+				;;
 			--history-file=*)
-							_arg_history_file="${_key##--history-file=}"
-							;;
+				_arg_history_file="${_key##--history-file=}"
+				;;
+			--dependencies)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_dependencies+=("$2")
+				shift
+				;;
+			--dependencies=*)
+				_arg_dependencies+=("${_key##--dependencies=}")
+				;;
 			--leftovers)
 				_arg_leftovers="on"
 				;;
@@ -497,6 +508,7 @@ print_debug()
 	echo -e " history: ${_arg_history}";
 	echo -e " history-offset: ${_arg_history_offset}";
 	echo -e " history-file: ${_arg_history_file}";
+	echo -e " dependencies: ${_arg_dependencies[*]}";
 	echo -e "	leftovers: ${_arg_leftovers}";
 	echo -e "	bang: ${_arg_bang}";
 	echo -e "	version-opt: ${_arg_version_opt}";
@@ -664,6 +676,10 @@ done
 for nested in "${_arg_nested[@]}"; do
 	eval "$SCRIPT_ROOT_DIR/nested/declaration $nested";
 done
+
+if [ "${#_arg_dependencies[@]}" -gt 0 ]; then
+	echo "# ${paCmtTrgr}dependencies ${_arg_dependencies[*]}";
+fi
 
 # generating parsing function
 echo "# ${paCmtTrgr}declarations-end
@@ -955,7 +971,21 @@ echo -e "
 on_interrupt() {
 	die "Process aborted!" 130;
 }
+"
 
+if [ "${#_arg_dependencies[@]}" -gt 0 ]; then
+	echo "__missing_dependencies=()";
+	for _dep in "${_arg_dependencies[@]}"; do
+		echo -e "if ! command -v \"$_dep\" &> /dev/null; then
+	__missing_dependencies+=(\"$_dep\");
+fi";
+	done
+	echo -e "if [ \"\${#__missing_dependencies[@]}\" -gt 0 ]; then
+	die \"Missing dependencies: \${__missing_dependencies[*]}\" 1;
+fi";
+fi
+
+echo -e "
 parse_commandline \"\$@\";
 handle_passed_args_count;
 assign_positional_args 1 \"\${_positionals[@]}\";
@@ -965,6 +995,7 @@ trap on_interrupt INT;
 if [[ "$hasSubCmd" == "0" ]]; then
 	echo -e "$(eval "$SCRIPT_ROOT_DIR/pos/subcmd-handle ${_arg_pos[0]}")";
 fi
+
 echo -e "
 # ${paCmtTrgr}parsing-end
 # print_debug \"\$@\"
