feat: add XDG Base Directory support for generated scripts
Add cross-platform XDG config/data/cache directory handling that users
can include in their generated scripts via --xdg option.

New features:
- --xdg <appname> option to enable XDG support
- --xdg-config, --xdg-data, --xdg-cache flags to control which dirs
- --xdg-config-file to customize config filename
- Generated helper functions: xdg_init(), xdg_config_dir(),
  xdg_save_config(), xdg_load_config(), etc.
- Cross-platform: Linux, macOS, Windows (Git Bash/MSYS2/Cygwin)

New files:
- bin/xdg/declaration, init, functions - XDG code generators
- tests/010_xdg.test.sh - 6 tests, 41 assertions
- docs/app/docs/xdg-config/page.tsx - documentation page

Modified:
- bin/generate - integrate XDG options
- bin/parse - handle @parseArger-xdg annotations
- bin/utils - add parsearger_get_xdg() extraction

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -31,8 +31,13 @@ fi
 # @parseArger opt nested "nested option declaration" --repeat
 # @parseArger opt history "add n history lines at the end of the file"
 # @parseArger opt history-offset "offset --history value by value"
-# @parseArger opt history-file "specify history file" --default-value "$HOME/.bash_history"
+# @parseArger opt history-file "specify history file" --default-value "/home/didi/.bash_history"
 # @parseArger opt dependencies "specify script dependencies" --repeat
+# @parseArger opt xdg "XDG app name for config/data/cache directories"
+# @parseArger opt xdg-config-file "XDG config file name" --default-value "config"
+# @parseArger flag xdg-config "enable XDG_CONFIG_HOME support" --on
+# @parseArger flag xdg-data "enable XDG_DATA_HOME support" --on
+# @parseArger flag xdg-cache "enable XDG_CACHE_HOME support"
 # @parseArger flag leftovers "accept extra arguments"
 # @parseArger flag bang "include shebang" --on
 # @parseArger flag version-opt "generate version opt handling" --on
@@ -92,9 +97,14 @@ _arg_verbose_level="0"
 _arg_nested=()
 _arg_history=
 _arg_history_offset=
-_arg_history_file="$HOME/.bash_history"
+_arg_history_file="/home/didi/.bash_history"
 _arg_dependencies=()
+_arg_xdg=
+_arg_xdg_config_file="config"
 # FLAGS
+_arg_xdg_config="on"
+_arg_xdg_data="on"
+_arg_xdg_cache="off"
 _arg_leftovers="off"
 _arg_bang="on"
 _arg_version_opt="on"
@@ -132,15 +142,20 @@ print_help()
 	echo -e "	--nested <nested>: nested option declaration, repeatable"
 	echo -e "	--history <history>: add n history lines at the end of the file"
 	echo -e "	--history-offset <history-offset>: offset --history value by value"
-	echo -e "	--history-file <history-file>: specify history file [default: ' $HOME/.bash_history ']"
+	echo -e "	--history-file <history-file>: specify history file [default: ' /home/didi/.bash_history ']"
 	echo -e "	--dependencies <dependencies>: specify script dependencies, repeatable"
+	echo -e "	--xdg <xdg>: XDG app name for config/data/cache directories"
+	echo -e "	--xdg-config-file <xdg-config-file>: XDG config file name [default: ' config ']"
+	echo -e "	--xdg-config|--no-xdg-config: enable XDG_CONFIG_HOME support, on by default (use --no-xdg-config to turn it off)"
+	echo -e "	--xdg-data|--no-xdg-data: enable XDG_DATA_HOME support, on by default (use --no-xdg-data to turn it off)"
+	echo -e "	--xdg-cache|--no-xdg-cache: enable XDG_CACHE_HOME support"
 	echo -e "	--leftovers|--no-leftovers: accept extra arguments"
 	echo -e "	--bang|--no-bang: include shebang, on by default (use --no-bang to turn it off)"
 	echo -e "	--version-opt|--no-version-opt: generate version opt handling, on by default (use --no-version-opt to turn it off)"
 	echo -e "	--use-verbose|--no-use-verbose: generate verbose level parser, on by default (use --no-use-verbose to turn it off)"
 	echo -e "	--parse-leftovers|--no-parse-leftovers: parse leftovers, force leftovers"
 	echo -e "Usage :
-	$0 [--pos <value>] [--opt <value>] [--flag <value>] [--set <value>] [--source <value>] [--help-message <value>] [--help-option <value>] [--help-short-option <value>] [--leftovers-name <value>] [--use-shebang <value>] [--set-version <value>] [--version-opt-name <value>] [--version-short-option <value>] [--die-fn-name <value>] [--log-fn-name <value>] [--verbose-opt-name <value>] [--verbose-level <value>] [--nested <value>] [--history <value>] [--history-offset <value>] [--history-file <value>] [--dependencies <value>] [--[no-]leftovers] [--[no-]bang] [--[no-]version-opt] [--[no-]use-verbose] [--[no-]parse-leftovers]";
+	$0 [--pos <value>] [--opt <value>] [--flag <value>] [--set <value>] [--source <value>] [--help-message <value>] [--help-option <value>] [--help-short-option <value>] [--leftovers-name <value>] [--use-shebang <value>] [--set-version <value>] [--version-opt-name <value>] [--version-short-option <value>] [--die-fn-name <value>] [--log-fn-name <value>] [--verbose-opt-name <value>] [--verbose-level <value>] [--nested <value>] [--history <value>] [--history-offset <value>] [--history-file <value>] [--dependencies <value>] [--xdg <value>] [--xdg-config-file <value>] [--[no-]xdg-config] [--[no-]xdg-data] [--[no-]xdg-cache] [--[no-]leftovers] [--[no-]bang] [--[no-]version-opt] [--[no-]use-verbose] [--[no-]parse-leftovers]";
 	fi
 
 }
@@ -403,6 +418,42 @@ parse_commandline()
 				_arg_dependencies+=("${_key##--dependencies=}")
 				;;
 			
+			--xdg)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_xdg="$2"
+				shift
+				;;
+			--xdg=*)
+				_arg_xdg="${_key##--xdg=}"
+				;;
+			
+			--xdg-config-file)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_xdg_config_file="$2"
+				shift
+				;;
+			--xdg-config-file=*)
+				_arg_xdg_config_file="${_key##--xdg-config-file=}"
+				;;
+			
+			--xdg-config)
+				_arg_xdg_config="on"
+				;;
+			--no-xdg-config)
+				_arg_xdg_config="off"
+				;;
+			--xdg-data)
+				_arg_xdg_data="on"
+				;;
+			--no-xdg-data)
+				_arg_xdg_data="off"
+				;;
+			--xdg-cache)
+				_arg_xdg_cache="on"
+				;;
+			--no-xdg-cache)
+				_arg_xdg_cache="off"
+				;;
 			--leftovers)
 				_arg_leftovers="on"
 				;;
@@ -498,6 +549,11 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		local _match_var="_match${_positional_name}";
+		local _regex="${!_match_var}";
+		if [ -n "$_regex" ]; then
+			[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
+		fi
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
@@ -531,6 +587,11 @@ print_debug()
 	echo -e "	history-offset: ${_arg_history_offset}";
 	echo -e "	history-file: ${_arg_history_file}";
 	echo -e "	dependencies: ${_arg_dependencies[*]}";
+	echo -e "	xdg: ${_arg_xdg}";
+	echo -e "	xdg-config-file: ${_arg_xdg_config_file}";
+	echo -e "	xdg-config: ${_arg_xdg_config}";
+	echo -e "	xdg-data: ${_arg_xdg_data}";
+	echo -e "	xdg-cache: ${_arg_xdg_cache}";
 	echo -e "	leftovers: ${_arg_leftovers}";
 	echo -e "	bang: ${_arg_bang}";
 	echo -e "	version-opt: ${_arg_version_opt}";
@@ -555,6 +616,7 @@ parse_commandline "$@";
 handle_passed_args_count;
 assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
+
 
 
 
@@ -652,6 +714,30 @@ if [ "$_arg_use_verbose" != "off" ]; then
 	"$SCRIPT_ROOT_DIR/verbose/declaration" "${verboseDecArg[@]}";
 else
 	verboseDecArg=("");
+fi
+
+# xdg
+if [ "$_arg_xdg" != "" ]; then
+	xdgDecArg=("$_arg_xdg");
+	if [ "$_arg_xdg_config" == "on" ]; then
+		xdgDecArg+=(--config);
+	else
+		xdgDecArg+=(--no-config);
+	fi
+	if [ "$_arg_xdg_data" == "on" ]; then
+		xdgDecArg+=(--data);
+	else
+		xdgDecArg+=(--no-data);
+	fi
+	if [ "$_arg_xdg_cache" == "on" ]; then
+		xdgDecArg+=(--cache);
+	else
+		xdgDecArg+=(--no-cache);
+	fi
+	if [ "$_arg_xdg_config_file" != "config" ]; then
+		xdgDecArg+=(--config-file "$_arg_xdg_config_file");
+	fi
+	"$SCRIPT_ROOT_DIR/xdg/declaration" "${xdgDecArg[@]}";
 fi
 
 # setting user variables
@@ -781,6 +867,11 @@ if [ "$_arg_use_verbose" != "off" ]; then
 	"$SCRIPT_ROOT_DIR/verbose/init" "${verboseDecArg[@]}";
 fi
 
+# xdg init
+if [ "$_arg_xdg" != "" ]; then
+	"$SCRIPT_ROOT_DIR/xdg/init" "${xdgDecArg[@]}";
+fi
+
 # help
 # TODO get the index of the subcommand arg to compare to total number of args
 #		2 selected because "tgt --help" is 2 args
@@ -843,6 +934,11 @@ echo -e "
 # verbose log function
 if [ "$_arg_use_verbose" != "off" ]; then
 	"$SCRIPT_ROOT_DIR/verbose/logger" "${verboseDecArg[@]}";
+fi
+
+# xdg helper functions
+if [ "$_arg_xdg" != "" ]; then
+	"$SCRIPT_ROOT_DIR/xdg/functions" "${xdgDecArg[@]}";
 fi
 
 # TODO: handle repeat-min and repeat-max
@@ -1040,6 +1136,10 @@ handle_passed_args_count;
 assign_positional_args 1 \"\${_positionals[@]}\";
 trap on_interrupt INT;
 ";
+# xdg_init call
+if [ "$_arg_xdg" != "" ]; then
+	echo "xdg_init;";
+fi
 for opt in "${_arg_opt[@]}"; do
 	eval "$SCRIPT_ROOT_DIR/opt/check-required $opt";
 done
diff --git a/utils/get_skills b/utils/get_skills
--- a/utils/get_skills
+++ b/utils/get_skills
@@ -217,8 +217,7 @@ handle_passed_args_count()
 {
 	local _required_args_string=""
 	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
-		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').
-	${_positionals[*]}" 1
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
 	fi
 	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}.
@@ -235,6 +234,11 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		local _match_var="_match${_positional_name}";
+		local _regex="${!_match_var}";
+		if [ -n "$_regex" ]; then
+			[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
+		fi
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
@@ -265,6 +269,7 @@ parse_commandline "$@";
 handle_passed_args_count;
 assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
+
 
 
 
