use parseArger on bin/generate

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -1,26 +1,22 @@
 #!/bin/bash
+# @parseArger-begin
+# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-declarations
+# @parseArger opt pos "positional argument declaration" --short p --repeat
+# @parseArger opt opt "optional arg declaration" --short o --repeat
+# @parseArger opt flag "flag declaration" --short f --repeat
+# @parseArger opt set "declare var" --short s --repeat
+# @parseArger opt source "file to source" --short l --repeat
+# @parseArger opt help-message "help message for the command" --short m --default-value "I send an SOS to the world"
+# @parseArger opt help-option "help option trigger"
+# @parseArger opt help-short-option "short help option"
+# @parseArger opt leftovers-name "extra arguments variable name" --default-value "leftovers"
+# @parseArger opt use-shebang "shebang executable" --default-value "/ben/bash"
+# @parseArger flag leftovers "accept extra arguments"
+# @parseArger flag bang "include shebang" --on
+# @parseArger-declarations-end
 
-# Created by argbash-init v2.10.0
-# ARG_OPTIONAL_REPEATED([pos],[],[positional arguments declarations])
-# ARG_OPTIONAL_REPEATED([opt],[],[optionnal arguments declarations])
-# ARG_OPTIONAL_REPEATED([flag],[],[flags declarations])
-# ARG_OPTIONAL_REPEATED([set],[],[variable declarations])
-# ARG_OPTIONAL_REPEATED([source],[],[file to source])
-# ARG_OPTIONAL_SINGLE([help-message],[],[general help message for the script],[I send an SOS to the world])
-# ARG_OPTIONAL_SINGLE([help-option],[],[option to trigger for the script])
-# ARG_OPTIONAL_SINGLE([help-short-option],[],[option to trigger for the script])
-# ARG_OPTIONAL_SINGLE([leftovers-name],[],[extra arguments variable name],[leftovers])
-# ARG_OPTIONAL_SINGLE([use-bang],[],[shebang executable],[/bin/bash])
-# ARG_OPTIONAL_BOOLEAN([leftovers],[],[accept extra arguments])
-# ARG_OPTIONAL_BOOLEAN([bang],[],[include shebang],[on])
-# ARG_HELP([generate the parsing code])
-# ARGBASH_GO()
-# needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
-# Argbash is a bash code generator used to get arguments parsing right.
-# Argbash is FREE SOFTWARE, see https://argbash.io for more info
-
-
+# @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
@@ -32,12 +28,14 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='h'
+	local first_option all_short_options=''
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
-# THE DEFAULTS INITIALIZATION - OPTIONALS
+# POSITIONALS ARGUMENTS
+_positionals=();
+# OPTIONALS ARGUMENTS
 _arg_pos=()
 _arg_opt=()
 _arg_flag=()
@@ -47,117 +45,146 @@ _arg_help_message="I send an SOS to the world"
 _arg_help_option=
 _arg_help_short_option=
 _arg_leftovers_name="leftovers"
-_arg_use_bang="/bin/bash"
+_arg_use_shebang="/ben/bash"
+# FLAGS
 _arg_leftovers="off"
 _arg_bang="on"
 
 
 print_help()
 {
-	printf '%s\n' "generate the parsing code"
-	printf 'Usage: %s [--pos <arg>] [--opt <arg>] [--flag <arg>] [--set <arg>] [--source <arg>] [--help-message <arg>] [--help-option <arg>] [--help-short-option <arg>] [--leftovers-name <arg>] [--use-bang <arg>] [--(no-)leftovers] [--(no-)bang] [-h|--help]\n' "$0"
-	printf '\t%s\n' "--pos: positional arguments declarations (empty by default)"
-	printf '\t%s\n' "--opt: optionnal arguments declarations (empty by default)"
-	printf '\t%s\n' "--flag: flags declarations (empty by default)"
-	printf '\t%s\n' "--set: variable declarations (empty by default)"
-	printf '\t%s\n' "--source: file to source (empty by default)"
-	printf '\t%s\n' "--help-message: general help message for the script (default: 'I send an SOS to the world')"
-	printf '\t%s\n' "--help-option: option to trigger for the script (no default)"
-	printf '\t%s\n' "--help-short-option: option to trigger for the script (no default)"
-	printf '\t%s\n' "--leftovers-name: extra arguments variable name (default: 'leftovers')"
-	printf '\t%s\n' "--use-bang: shebang executable (default: '/bin/bash')"
-	printf '\t%s\n' "--leftovers, --no-leftovers: accept extra arguments (off by default)"
-	printf '\t%s\n' "--bang, --no-bang: include shebang (on by default)"
-	printf '\t%s\n' "-h, --help: Prints help"
+	echo -e "I send an SOS to the world:"
+	echo -e "	-p, --pos <pos>: positional argument declaration, repeatable"
+	echo -e "	-o, --opt <opt>: optional arg declaration, repeatable"
+	echo -e "	-f, --flag <flag>: flag declaration, repeatable"
+	echo -e "	-s, --set <set>: declare var, repeatable"
+	echo -e "	-l, --source <source>: file to source, repeatable"
+	echo -e "	-m, --help-message <help-message>: help message for the command [default: ' I send an SOS to the world ']"
+	echo -e "	--help-option <help-option>: help option trigger"
+	echo -e "	--help-short-option <help-short-option>: short help option"
+	echo -e "	--leftovers-name <leftovers-name>: extra arguments variable name [default: ' leftovers ']"
+	echo -e "	--use-shebang <use-shebang>: shebang executable [default: ' /ben/bash ']"
+	echo -e "	--leftovers|--no-leftovers: accept extra arguments"
+	echo -e "	--bang|--no-bang: include shebang, on by default (use --no-bang to turn it off)"
+	echo -e "Usage :
+	$0 [--pos <value>] [--opt <value>] [--flag <value>] [--set <value>] [--source <value>] [--help-message <value>] [--help-option <value>] [--help-short-option <value>] [--leftovers-name <value>] [--use-shebang <value>] [--[no-]leftovers] [--[no-]bang]"
 }
-
 
 parse_commandline()
 {
+	_positionals_count=0
 	while test $# -gt 0
 	do
 		_key="$1"
 		case "$_key" in
-			--pos)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-p|--pos)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_pos+=("$2")
 				shift
 				;;
 			--pos=*)
 				_arg_pos+=("${_key##--pos=}")
 				;;
-			--opt)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-p*)
+				_arg_pos+=("${_key##-p}")
+				;;
+			
+			-o|--opt)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_opt+=("$2")
 				shift
 				;;
 			--opt=*)
 				_arg_opt+=("${_key##--opt=}")
 				;;
-			--flag)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-o*)
+				_arg_opt+=("${_key##-o}")
+				;;
+			
+			-f|--flag)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_flag+=("$2")
 				shift
 				;;
 			--flag=*)
 				_arg_flag+=("${_key##--flag=}")
 				;;
-			--set)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-f*)
+				_arg_flag+=("${_key##-f}")
+				;;
+			
+			-s|--set)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_set+=("$2")
 				shift
 				;;
 			--set=*)
 				_arg_set+=("${_key##--set=}")
 				;;
-			--source)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-s*)
+				_arg_set+=("${_key##-s}")
+				;;
+			
+			-l|--source)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_source+=("$2")
 				shift
 				;;
 			--source=*)
 				_arg_source+=("${_key##--source=}")
 				;;
-			--help-message)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+			-l*)
+				_arg_source+=("${_key##-l}")
+				;;
+			
+			-m|--help-message)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_help_message="$2"
 				shift
 				;;
 			--help-message=*)
 				_arg_help_message="${_key##--help-message=}"
 				;;
+			-m*)
+				_arg_help_message="${_key##-m}"
+				;;
+			
 			--help-option)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_help_option="$2"
 				shift
 				;;
 			--help-option=*)
 				_arg_help_option="${_key##--help-option=}"
 				;;
+			
 			--help-short-option)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_help_short_option="$2"
 				shift
 				;;
 			--help-short-option=*)
 				_arg_help_short_option="${_key##--help-short-option=}"
 				;;
+			
 			--leftovers-name)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_leftovers_name="$2"
 				shift
 				;;
 			--leftovers-name=*)
 				_arg_leftovers_name="${_key##--leftovers-name=}"
 				;;
-			--use-bang)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_use_bang="$2"
+			
+			--use-shebang)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_use_shebang="$2"
 				shift
 				;;
-			--use-bang=*)
-				_arg_use_bang="${_key##--use-bang=}"
+			--use-shebang=*)
+				_arg_use_shebang="${_key##--use-shebang=}"
 				;;
+			
 			--no-leftovers|--leftovers)
 				_arg_leftovers="on"
 				test "${1:0:5}" = "--no-" && _arg_leftovers="off"
@@ -167,30 +194,80 @@ parse_commandline()
 				test "${1:0:5}" = "--no-" && _arg_bang="off"
 				;;
 			-h|--help)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			-h*)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			*)
-				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
 				;;
 		esac
 		shift
 	done
 }
 
-parse_commandline "$@"
 
-# OTHER STUFF GENERATED BY Argbash
+handle_passed_args_count()
+{
+	local _required_args_string=""
+	test "${_positionals_count}" -le 0 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+	test "${_positionals_count}" -ge 0 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+}
 
-### END OF CODE GENERATED BY Argbash (sortof) ### ])
-# [ <-- needed because of Argbash
+
+assign_positional_args()
+{
+	local _positional_name _shift_for=$1;
+	_positional_names="";
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names};do
+		test $# -gt 0 || break;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		shift;
+	done
+}
+
+print_debug()
+{
+	print_help
+	# shellcheck disable=SC2145
+	echo "DEBUG: $0 $@";
+	
+	echo -e "\tpos: ${_arg_pos | sed 's/-/_/g'}";
+	echo -e "\topt: ${_arg_opt | sed 's/-/_/g'}";
+	echo -e "\tflag: ${_arg_flag | sed 's/-/_/g'}";
+	echo -e "\tset: ${_arg_set | sed 's/-/_/g'}";
+	echo -e "\tsource: ${_arg_source | sed 's/-/_/g'}";
+	echo -e "\thelp-message: ${_arg_help-message | sed 's/-/_/g'}";
+	echo -e "\thelp-option: ${_arg_help-option | sed 's/-/_/g'}";
+	echo -e "\thelp-short-option: ${_arg_help-short-option | sed 's/-/_/g'}";
+	echo -e "\tleftovers-name: ${_arg_leftovers-name | sed 's/-/_/g'}";
+	echo -e "\tuse-shebang: ${_arg_use-shebang | sed 's/-/_/g'}";
+	echo -e "\tleftovers: ${_arg_leftovers | sed 's/-/_/g'}";
+	echo -e "\tbang: ${_arg_bang | sed 's/-/_/g'}";
+
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
 
 
-# vvv  PLACE YOUR CODE HERE  vvv
+# @parseArger-parsing-end
+# print_debug "$@"
+# @parseArger-end
+
 SCRIPT_ROOT_DIR=$(
   cd "$(dirname "${BASH_SOURCE[0]}")"
   pwd -P
@@ -206,6 +283,8 @@ optNames=();
 optArgNames=();
 flagNames=();
 flagArgNames=();
+paCmtTrgr="@parse";
+paCmtTrgr+="Arger-";
 
 posI=0;
 for pos in "${_arg_pos[@]}"; do
@@ -243,7 +322,7 @@ if [ "$_arg_bang" != "off" ]; then
 fi
 
 # parsing
-echo -e "# @parseArger-begin";
+echo -e "# ${paCmtTrgr}begin";
 
 # help
 helpDecArg=("$_arg_help_message");
@@ -258,7 +337,7 @@ fi
 # setting user variables
 if [ "${#_arg_set[@]}" -gt 0 ]; then
 	for _set in "${_arg_set[@]}"; do
-		echo "# @parseArger-set $_set";
+		echo "# ${paCmtTrgr}set $_set";
 		echo -e "$_set";
 	done
 fi
@@ -266,18 +345,18 @@ fi
 # sourcing user files
 if [ "${#_arg_source[@]}" -gt 0 ]; then
 	for _source in "${_arg_source[@]}"; do
-		echo "# @parseArger-source $_source";
+		echo "# ${paCmtTrgr}source $_source";
 		echo -e "source \"$_source\";";
 	done
 fi
 
 # leftovers
 if [ "$_arg_leftovers" == "on" ]; then
-	echo -e "# @parseArger-leftovers $_arg_leftovers_name";
+	echo -e "# ${paCmtTrgr}leftovers $_arg_leftovers_name";
 fi
 
 # argument declarations
-echo -e "# @parseArger-declarations";
+echo -e "# ${paCmtTrgr}declarations";
 for pos in "${_arg_pos[@]}"; do
 	eval "$SCRIPT_ROOT_DIR/pos/declaration $pos";
 done
@@ -288,9 +367,9 @@ for flag in "${_arg_flag[@]}"; do
 	eval "$SCRIPT_ROOT_DIR/flag/declaration $flag";
 done
 # generating parsing function
-echo "# @parseArger-declarations-end
+echo "# ${paCmtTrgr}declarations-end
 
-# @parseArger-parsing
+# ${paCmtTrgr}parsing
 die()
 {
 	local _ret=\"\${2:-1}\"
@@ -465,10 +544,6 @@ assign_positional_args 1 \"\${_positionals[@]}\";
 trap on_interrupt INT;
 
 
-# @parseArger-parsing-end
+# ${paCmtTrgr}parsing-end
 # print_debug \"\$@\"
-# @parseArger-end";
-
-# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
-
-# ] <-- needed because of Argbash
+# ${paCmtTrgr}end";
