subcommand can use leftovers + subcommand can use directory as target + subcommand autorun

diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -585,6 +585,7 @@ echo "# ${paCmtTrgr}declarations-end
 
 # ${paCmtTrgr}utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR=\"\$(cd \"\$(dirname \"\${BASH_SOURCE[0]}\")\" && pwd -P)\";
 # ${paCmtTrgr}utils-end
 
 # ${paCmtTrgr}parsing
@@ -592,7 +593,7 @@ die()
 {
 	local _ret=\"\${2:-1}\"
 	test \"\${_PRINT_HELP:-no}\" = yes && print_help >&2
-	echo -e \"\$1\" >&2
+	log \"\$1\" -3 >&2
 	exit \"\${_ret}\"
 }
 
@@ -755,14 +756,21 @@ fi
 	for _positional_name in \${_positional_names};do
 		test \$# -gt 0 || break;";
 	if [ "$_arg_leftovers" == "off" ]; then
-		echo "		eval \"if [ \\\"\\\$_one_of\${_positional_name}\\\" != \\\"\\\" ];then [[ \\\"\\\${_one_of\${_positional_name}[*]}\\\" =~ \\\"\\\${1}\\\" ]];fi\" || die \"\${_positional_name} must be one of: \$(eval \"echo \\\"\\\${_one_of\${_positional_name}[*]}\\\"\")\" 1";
+		echo -e "		eval \"if [ \\\"\\\$_one_of\${_positional_name}\\\" != \\\"\\\" ];then [[ \\\"\\\${_one_of\${_positional_name}[*]}\\\" =~ \\\"\\\${1}\\\" ]];fi\" || die \"\${_positional_name} must be one of: \$(eval \"echo \\\"\\\${_one_of\${_positional_name}[*]}\\\"\")\" 1;";
+		if [[ "$hasSubCmd" == "0" ]]; then
+			echo -e "		$(eval "$SCRIPT_ROOT_DIR/pos/subcmd-assign ${_arg_pos[0]}")";
+		fi
 	else
 		echo "		if ! [[ \"\$_positional_name\" =~ \"_arg_$_arg_leftovers_name\" ]];then
-			eval \"if [ \\\"\\\$_one_of\${_positional_name}\\\" != \\\"\\\" ];then [[ \\\"\\\${_one_of\${_positional_name}[*]}\\\" =~ \\\"\\\${1}\\\" ]];fi\" || die \"\${_positional_name} must be one of: \$(eval \"echo \\\"\\\${_one_of\${_positional_name}[*]}\\\"\")\" 1
-		fi";
+			eval \"if [ \\\"\\\$_one_of\${_positional_name}\\\" != \\\"\\\" ];then [[ \\\"\\\${_one_of\${_positional_name}[*]}\\\" =~ \\\"\\\${1}\\\" ]];fi\" || die \"\${_positional_name} must be one of: \$(eval \"echo \\\"\\\${_one_of\${_positional_name}[*]}\\\"\")\" 1;"
+		if [[ "$hasSubCmd" == "0" ]]; then
+			echo -e "			$(eval "$SCRIPT_ROOT_DIR/pos/subcmd-assign ${_arg_pos[0]}")";
+		fi
+		echo "		fi";
 	fi
-	echo -e "eval \"\$_positional_name=\\\${1}\" || die \"Error during argument parsing, possibly an ParseArger bug.\" 1;
-		shift;
+	echo -e "		eval \"\$_positional_name=\\\${1}\" || die \"Error during argument parsing, possibly an ParseArger bug.\" 1;";
+
+	echo -e "		shift;
 	done
 }
 
@@ -813,7 +821,11 @@ handle_passed_args_count;
 assign_positional_args 1 \"\${_positionals[@]}\";
 trap on_interrupt INT;
 
-
+";
+if [[ "$hasSubCmd" == "0" ]]; then
+	echo -e "$(eval "$SCRIPT_ROOT_DIR/pos/subcmd-handle ${_arg_pos[0]}")";
+fi
+echo -e "
 # ${paCmtTrgr}parsing-end
 # print_debug \"\$@\"
 # ${paCmtTrgr}end";
diff --git a/bin/pos/help b/bin/pos/help
--- a/bin/pos/help
+++ b/bin/pos/help
@@ -2,19 +2,25 @@
 # @parseArger-begin
 # @parseArger-help "parseArger help string for arguments" --option "help" --short-option "h"
 # @parseArger-version "0.1" --option "version" --short-option "v"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
-# @parseArger pos arg-name "positional argument name"
-# @parseArger pos description "positional argument description"
+# @parseArger pos arg-name "positional argument name" --subcommand-variable "__subcommand" --subcommand
+# @parseArger pos description "positional argument description" --subcommand-variable "__subcommand" --subcommand
 # @parseArger opt repeat-min "minimum repeatition forces --repeat" --default-value "1"
 # @parseArger opt repeat-max "maximum repeatition forces --repeat"
 # @parseArger opt one-of "accepted values" --repeat
+# @parseArger opt subcommand-directory "directory containing subcommands, force subcommand"
+# @parseArger opt subcommand-variable "array variable containing subcommand parts, force subcommand" --default-value "__subcommand"
+# @parseArger flag subcommand-run "run subcommand, forces sub command"
 # @parseArger flag repeat "repeatable" --short r
 # @parseArger flag optional "optional"
 # @parseArger flag subcommand "is a subcommand"
+# @parseArger flag subcommand-use-leftovers "add leftover arguments to subcommand, forces subcommand"
 # @parseArger-declarations-end
 
 # @parseArger-utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
@@ -22,7 +28,7 @@ die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo -e "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -37,19 +43,37 @@ begins_with_short_option()
 # POSITIONALS ARGUMENTS
 _positionals=();
 _arg_arg_name="";
+_arg_subcommand_arg="_arg_arg_name";
+__subcommand=();
 _arg_description="";
+_arg_subcommand_arg="_arg_description";
+__subcommand=();
 # OPTIONALS ARGUMENTS
 _arg_repeat_min="1"
 _arg_repeat_max=
 _arg_one_of=()
+_arg_subcommand_directory=
+_arg_subcommand_variable="__subcommand"
 # FLAGS
+_arg_subcommand_run="off"
 _arg_repeat="off"
 _arg_optional="off"
 _arg_subcommand="off"
+_arg_subcommand_use_leftovers="off"
+_verbose_level="0";
+
 
 
 print_help()
 {
+	_triggerSCHelp=1;
+
+	if [ "${#_positionals[@]}" -ge 1 ]; then
+		echo "$0 sub command help
+	"
+		_triggerSCHelp=0;
+	else
+	
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
@@ -59,13 +83,51 @@ print_help()
 	echo -e "	--repeat-min <repeat-min>: minimum repeatition forces --repeat [default: ' 1 ']"
 	echo -e "	--repeat-max <repeat-max>: maximum repeatition forces --repeat"
 	echo -e "	--one-of <one-of>: accepted values, repeatable"
+	echo -e "	--subcommand-directory <subcommand-directory>: directory containing subcommands, force subcommand"
+	echo -e "	--subcommand-variable <subcommand-variable>: array variable containing subcommand parts, force subcommand [default: ' __subcommand ']"
+	echo -e "	--subcommand-run|--no-subcommand-run: run subcommand, forces sub command"
 	echo -e "	-r|--repeat|--no-repeat: repeatable"
 	echo -e "	--optional|--no-optional: optional"
 	echo -e "	--subcommand|--no-subcommand: is a subcommand"
+	echo -e "	--subcommand-use-leftovers|--no-subcommand-use-leftovers: add leftover arguments to subcommand, forces subcommand"
 	echo -e "Usage :
-	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--[no-]repeat] [--[no-]optional] [--[no-]subcommand]";
+	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--subcommand-directory <value>] [--subcommand-variable <value>] [--[no-]subcommand-run] [--[no-]repeat] [--[no-]optional] [--[no-]subcommand] [--[no-]subcommand-use-leftovers]";
 	fi
 
+	fi
+	
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}";
+	fi
 }
 
 parse_commandline()
@@ -102,6 +164,30 @@ parse_commandline()
 				_arg_one_of+=("${_key##--one-of=}")
 				;;
 			
+			--subcommand-directory)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_subcommand_directory="$2"
+				shift
+				;;
+			--subcommand-directory=*)
+				_arg_subcommand_directory="${_key##--subcommand-directory=}"
+				;;
+			
+			--subcommand-variable)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_subcommand_variable="$2"
+				shift
+				;;
+			--subcommand-variable=*)
+				_arg_subcommand_variable="${_key##--subcommand-variable=}"
+				;;
+			
+			--subcommand-run)
+				_arg_subcommand_run="on"
+				;;
+			--no-subcommand-run)
+				_arg_subcommand_run="off"
+				;;
 			-r|--repeat)
 				_arg_repeat="on"
 				;;
@@ -120,13 +206,17 @@ parse_commandline()
 			--no-subcommand)
 				_arg_subcommand="off"
 				;;
+			--subcommand-use-leftovers)
+				_arg_subcommand_use_leftovers="on"
+				;;
+			--no-subcommand-use-leftovers)
+				_arg_subcommand_use_leftovers="off"
+				;;
 			-h|--help)
 				print_help;
-				exit 0;
 				;;
 			-h*)
 				print_help;
-				exit 0;
 				;;
 			-v|--version)
 				print_version;
@@ -136,6 +226,15 @@ parse_commandline()
 				print_version;
 				exit 0;
 				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -167,8 +266,9 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		__subcommand+=("$_SCRIPT_DIR/${1}");
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -184,9 +284,13 @@ print_debug()
 	echo -e "\trepeat-min: ${_arg_repeat_min}";
 	echo -e "\trepeat-max: ${_arg_repeat_max}";
 	echo -e "\tone-of: ${_arg_one_of[*]}";
+	echo -e "\tsubcommand-directory: ${_arg_subcommand_directory}";
+	echo -e "\tsubcommand-variable: ${_arg_subcommand_variable}";
+	echo -e "\tsubcommand-run: ${_arg_subcommand_run}";
 	echo -e "\trepeat: ${_arg_repeat}";
 	echo -e "\toptional: ${_arg_optional}";
 	echo -e "\tsubcommand: ${_arg_subcommand}";
+	echo -e "\tsubcommand-use-leftovers: ${_arg_subcommand_use_leftovers}";
 
 }
 
@@ -209,6 +313,14 @@ trap on_interrupt INT;
 # print_debug "$@"
 # @parseArger-end
 
+SCRIPT_ROOT_DIR="$(
+  cd "$(dirname "${BASH_SOURCE[0]}")"
+  pwd -P
+)/..";
+
+# shellcheck source=../utils
+source "${SCRIPT_ROOT_DIR}/utils";
+
 optHelp="${_arg_arg_name}: ${_arg_description}";
 
 if [ "$_arg_repeat_min" -gt "1" ] || [ "$_arg_repeat_max" != "" ]; then
@@ -224,6 +336,35 @@ fi
 
 if [ "$_arg_default_value" != "" ]; then
 	optHelp+=" [default: '${_arg_default_value}']";
+fi
+
+if [ "$_arg_subcommand_variable" != "" ]; then
+	_arg_subcommand="on";
+fi
+
+if [ "$_arg_subcommand_directory" != "" ]; then
+	if [ -d "$_arg_subcommand_directory" ]; then
+		_arg_subcommand="on";
+		# Searching in the current directory
+		for file in "$_arg_subcommand_directory/"*; do
+			tname="$(basename "$file")";
+			if ! [[ "${_arg_one_of[*]}" =~ " $tname " ]] && [ -f "$file" ] && parsearger_is_pa_file "$file"; then
+				_arg_one_of+=("$tname");
+			fi
+		done
+	fi
+fi
+
+if [ "$_arg_subcommand_run" != "off" ]; then
+	_arg_subcommand="on";
+fi
+
+if [ "$_arg_subcommand_use_leftovers" != "off" ]; then
+	_arg_subcommand="on";
+fi
+
+if [ "$_arg_subcommand" != "off" ]; then
+	outStr+=" --subcommand";
 fi
 
 if [ "${#_arg_one_of[@]}" -gt 0 ]; then
