...

diff --git a/parseArger b/parseArger
--- a/parseArger
+++ b/parseArger
@@ -7,13 +7,14 @@
 export PARSEARGER_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P);
 # @parseArger-leftovers leftovers
 # @parseArger-declarations
-# @parseArger pos target "what to do" --subcommand --one-of "parse" --one-of "generate" --one-of "document" --one-of "bulk-parse" --one-of "completely"
+# @parseArger pos target "what to do" --subcommand-directory "bin" --subcommand-use-leftovers --subcommand --one-of "parse" --one-of "generate" --one-of "document" --one-of "bulk-parse" --one-of "completely" --one-of "completely" --one-of "parse" --one-of "parse"
 # @parseArger opt output "create file with command output at value"
 # @parseArger flag prepend "add output on top of file"
 # @parseArger-declarations-end
 
 # @parseArger-utils
 _helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
@@ -21,7 +22,7 @@ die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo -e "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -38,6 +39,7 @@ _positionals=();
 _arg_target="";
 _one_of_arg_target=("parse" "generate" "document" "bulk-parse" "completely" );
 _arg_subcommand_arg="_arg_target";
+__subcommand=();
 # OPTIONALS ARGUMENTS
 _arg_output=
 # FLAGS
@@ -101,7 +103,7 @@ log() {
 				_arg_COLOR="\033[0m";
 				;;
 		esac
-		echo -e "${_arg_COLOR}${_arg_msg}";
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
 	fi
 }
 
@@ -184,9 +186,10 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
-			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+			__subcommand+=("$_SCRIPT_DIR/bin/${1}");
 		fi
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -219,6 +222,11 @@ assign_positional_args 1 "${_positionals[@]}";
 trap on_interrupt INT;
 
 
+if [ "$_triggerSCHelp" == "0" ];then
+	__subcommand+=("--help");
+fi
+__subcommand+=("${_arg_leftovers[@]}");
+
 # @parseArger-parsing-end
 # print_debug "$@"
 # @parseArger-end
@@ -226,12 +234,12 @@ if [ "$_triggerSCHelp" == "0" ]; then
 	_arg_leftovers+=("--help");
 fi
 
+cmdOutStr=$("${__subcommand[@]}");
+
 if [ "$_arg_output" == "" ]; then
-	if [ "$_arg_target" != "" ]; then
-		"$PARSEARGER_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}";
-	fi
+	echo -e "${cmdOutStr}";
 else
-	output="$("$PARSEARGER_ROOT_DIR/bin/$_arg_target" "${_arg_leftovers[@]}")";
+	output="${cmdOutStr}";
 	
 	if [ "$_arg_output" != "" ]; then
 		if [[ -f "$_arg_output" ]]; then
