bin/flag/* to parseArger + fix lt gt error

diff --git a/bin/flag/help b/bin/flag/help
--- a/bin/flag/help
+++ b/bin/flag/help
@@ -1,57 +1,59 @@
 #!/bin/bash
+# @parseArger-begin
+# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-declarations
+# @parseArger pos arg-name "positional argument name"
+# @parseArger pos description "positional argument description"
+# @parseArger opt short "short form" --short s
+# @parseArger flag on "on by default"
+# @parseArger-declarations-end
 
-# Created by argbash-init v2.10.0
-# ARG_OPTIONAL_SINGLE([short],[s],[short option])
-# ARG_OPTIONAL_SINGLE([template])
-# ARG_OPTIONAL_BOOLEAN([on],[],[flag on by default])
-# ARG_POSITIONAL_SINGLE([arg-name],[flag name])
-# ARG_POSITIONAL_SINGLE([description],[flag description])
-# ARG_DEFAULTS_POS([])
-# ARG_HELP([generate the parseArg help string for flag])
-# ARGBASH_GO()
-# needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
-# Argbash is a bash code generator used to get arguments parsing right.
-# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
 
-
+# @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	echo -e "$1" >&2
 	exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-	local first_option all_short_options='sh'
+	local first_option all_short_options=''
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
-# THE DEFAULTS INITIALIZATION - POSITIONALS
-_positionals=()
-_arg_arg_name=
-_arg_description=
-# THE DEFAULTS INITIALIZATION - OPTIONALS
+# POSITIONALS ARGUMENTS
+_positionals=();
+_arg_arg_name="";
+_arg_description="";
+# OPTIONALS ARGUMENTS
 _arg_short=
-_arg_template=
+# FLAGS
 _arg_on="off"
 
 
 print_help()
 {
-	printf '%s\n' "generate the parseArg help string for flag"
-	printf 'Usage: %s [-s|--short <arg>] [--template <arg>] [--(no-)on] [-h|--help] <arg-name> <description>\n' "$0"
-	printf '\t%s\n' "<arg-name>: flag name"
-	printf '\t%s\n' "<description>: flag description"
-	printf '\t%s\n' "-s, --short: short option (no default)"
-	printf '\t%s\n' "--on, --no-on: flag on by default (off by default)"
-	printf '\t%s\n' "-h, --help: Prints help"
-}
 
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "I send an SOS to the world:"
+	echo -e "	arg-name: positional argument name"
+	echo -e "	description: positional argument description"
+	echo -e "	-s, --short <short>: short form"
+	echo -e "	--on|--no-on: on by default"
+	echo -e "Usage :
+	$0 <arg-name> <description> [--short <value>] [--[no-]on]";
+	fi
+
+}
 
 parse_commandline()
 {
@@ -61,7 +63,7 @@ parse_commandline()
 		_key="$1"
 		case "$_key" in
 			-s|--short)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_short="$2"
 				shift
 				;;
@@ -71,25 +73,18 @@ parse_commandline()
 			-s*)
 				_arg_short="${_key##-s}"
 				;;
-			--template)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_template="$2"
-				shift
-				;;
-			--template=*)
-				_arg_template="${_key##--template=}"
-				;;
+			
 			--no-on|--on)
 				_arg_on="on"
 				test "${1:0:5}" = "--no-" && _arg_on="off"
 				;;
 			-h|--help)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			-h*)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			*)
 				_last_positional="$1"
@@ -104,37 +99,58 @@ parse_commandline()
 
 handle_passed_args_count()
 {
-	local _required_args_string="'arg-name' and 'description'"
-	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+	local _required_args_string="arg-name description"
+	if [ "${_positionals_count}" -gt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').
+	${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
 assign_positional_args()
 {
-	local _positional_name _shift_for=$1
-	_positional_names="_arg_arg_name _arg_description "
-
+	local _positional_name _shift_for=$1;
+	_positional_names="_arg_arg_name _arg_description ";
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
-		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-		shift
+	for _positional_name in ${_positional_names};do
+		test $# -gt 0 || break;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
+		shift;
 	done
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_debug()
+{
+	print_help
+	# shellcheck disable=SC2145
+	echo "DEBUG: $0 $@";
+	
+	echo -e "\targ-name: ${_arg_arg_name}";
+	echo -e "\tdescription: ${_arg_description}";
+	echo -e "\tshort: ${_arg_short | sed 's/-/_/g'}";
+	echo -e "\ton: ${_arg_on | sed 's/-/_/g'}";
 
-# OTHER STUFF GENERATED BY Argbash
+}
 
-### END OF CODE GENERATED BY Argbash (sortof) ### ])
-# [ <-- needed because of Argbash
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
 
 
-# vvv  PLACE YOUR CODE HERE  vvv
+# @parseArger-parsing-end
+# print_debug "$@"
+# @parseArger-end
+
 optHelp="--${_arg_arg_name}|--no-${_arg_arg_name}: ${_arg_description}";
 
 if [ "$_arg_short" != "" ]; then
@@ -145,7 +161,3 @@ if [ "$_arg_on" != "off" ]; then
 fi
 
 echo -e "	echo -e \"\t${optHelp}\"";
-
-# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
-
-# ] <-- needed because of Argbash
diff --git a/bin/generate b/bin/generate
--- a/bin/generate
+++ b/bin/generate
@@ -224,10 +224,10 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string=""
-	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
 		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 	fi
-	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}." 1;
 	fi
 }
@@ -241,7 +241,7 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -396,7 +396,7 @@ die()
 {
 	local _ret=\"\${2:-1}\"
 	test \"\${_PRINT_HELP:-no}\" = yes && print_help >&2
-	echo \"\$1\" >&2
+	echo -e \"\$1\" >&2
 	exit \"\${_ret}\"
 }
 
@@ -517,13 +517,13 @@ handle_passed_args_count()
 	local _required_args_string=\"${reqPos[*]}\"";
 
 if [ "$_arg_leftovers" == "off" ]; then
-	echo -e "	if [ \"\${_positionals_count}\" -lt ${maxPos} ] && [ \"\$_helpHasBeenPrinted\" == \"1\" ];then
-		_PRINT_HELP=yes die \"FATAL ERROR: There were spurious positional arguments --- we expect at most $maxPos (namely: \$_required_args_string), but got \${_positionals_count} (the last one was: '\${_last_positional}').\" 1
+	echo -e "	if [ \"\${_positionals_count}\" -gt ${maxPos} ] && [ \"\$_helpHasBeenPrinted\" == \"1\" ];then
+		_PRINT_HELP=yes die \"FATAL ERROR: There were spurious positional arguments --- we expect at most $maxPos (namely: \$_required_args_string), but got \${_positionals_count} (the last one was: '\${_last_positional}').\\n\\t\${_positionals[*]}\" 1
 	fi";
 fi
 
-	echo -e "	if [ \"\${_positionals_count}\" -gt ${minPos} ] && [ \"\$_helpHasBeenPrinted\" == \"1\" ];then
-		_PRINT_HELP=yes die \"FATAL ERROR: Not enough positional arguments - we require at least $minPos (namely: \$_required_args_string), but got only \${_positionals_count}.\" 1;
+	echo -e "	if [ \"\${_positionals_count}\" -lt ${minPos} ] && [ \"\$_helpHasBeenPrinted\" == \"1\" ];then
+		_PRINT_HELP=yes die \"FATAL ERROR: Not enough positional arguments - we require at least $minPos (namely: \$_required_args_string), but got only \${_positionals_count}.\\n\\t\${_positionals[*]}\" 1;
 	fi
 }
 
@@ -551,7 +551,7 @@ fi
 			eval \"if [ \\\"\\\$_one_of\${_positional_name}\\\" != \\\"\\\" ];then [[ \\\"\\\${_one_of\${_positional_name}[*]}\\\" =~ \\\"\\\${1}\\\" ]];fi\" || die \"\${_positional_name} must be one of: \$(eval \"echo \\\"\\\${_one_of\${_positional_name}[*]}\\\"\")\" 1
 		fi";
 	fi
-	echo -e "eval \"\$_positional_name=\\\${1}\" || die \"Error during argument parsing, possibly an Argbash bug.\" 1;
+	echo -e "eval \"\$_positional_name=\\\${1}\" || die \"Error during argument parsing, possibly an ParseArger bug.\" 1;
 		shift;
 	done
 }
