feat: add --env, --match, and --required support to parser generator

diff --git a/bin/opt/check-required b/bin/opt/check-required
--- a/bin/opt/check-required
+++ b/bin/opt/check-required
@@ -1,32 +1,25 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "parseArger init string for agruments" --option "help" --short-option "h"
+# @parseArger-help "check if option is required" --option "help" --short-option "h"
 # @parseArger-version "0.1" --option "version" --short-option "v"
 # @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
-# @parseArger-leftovers leftovers --parse
-_has_colors=0
-if [ -t 1 ]; then # Check if stdout is a terminal
-	ncolors=$(tput colors 2>/dev/null)
-	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
-		_has_colors=1
-	fi
-fi
 # @parseArger-declarations
 # @parseArger pos arg-name "positional argument name"
 # @parseArger pos description "positional argument description"
-# @parseArger opt repeat-min "minimum repeatition forces --repeat" --default-value "1"
-# @parseArger opt repeat-max "maximum repeatition forces --repeat"
+# @parseArger opt repeat-min "minimum repeatition forces repeat" --default-value "1"
+# @parseArger opt repeat-max "maximum repeatition forces repeat"
 # @parseArger opt one-of "accepted values" --repeat
-# @parseArger opt subcommand-directory "directory containing subcommands, force subcommand, list parseArger script in directory to fill --one-of"
-# @parseArger opt subcommand-variable "array variable containing subcommand parts, force subcommand" --default-value "__subcommand"
+# @parseArger opt default-value "value" --short d --repeat
+# @parseArger opt short "short form" --short s
+# @parseArger opt alias "option alias" --repeat
+# @parseArger opt empty-value "value for empty option"
 # @parseArger opt complete "bash built-in completely function" --repeat
 # @parseArger opt complete-custom "completely custom dynamic suggestion" --repeat
+# @parseArger opt env "environment variable name"
 # @parseArger opt match "regex match validation"
-# @parseArger flag subcommand-run "run subcommand, forces sub command"
 # @parseArger flag repeat "repeatable" --short r
-# @parseArger flag optional "optional"
-# @parseArger flag subcommand "is a subcommand"
-# @parseArger flag subcommand-use-leftovers "add leftover arguments to subcommand, forces subcommand"
+# @parseArger flag empty "use option as flag"
+# @parseArger flag required "make option mandatory" --short q
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -66,17 +59,18 @@ _arg_description="";
 _arg_repeat_min="1"
 _arg_repeat_max=
 _arg_one_of=()
-_arg_subcommand_directory=
-_arg_subcommand_variable="__subcommand"
+_arg_default_value=()
+_arg_short=
+_arg_alias=()
+_arg_empty_value=
 _arg_complete=()
 _arg_complete_custom=()
+_arg_env=
 _arg_match=
 # FLAGS
-_arg_subcommand_run="off"
 _arg_repeat="off"
-_arg_optional="off"
-_arg_subcommand="off"
-_arg_subcommand_use_leftovers="off"
+_arg_empty="off"
+_arg_required="off"
 # NESTED
 # LEFTOVERS
 _arg_leftovers=()
@@ -92,24 +86,25 @@ print_help()
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
-		echo -e "parseArger init string for agruments:"
+		echo -e "check if option is required:"
 	echo -e "	arg-name: positional argument name"
 	echo -e "	description: positional argument description"
-	echo -e "	--repeat-min <repeat-min>: minimum repeatition forces --repeat [default: ' 1 ']"
-	echo -e "	--repeat-max <repeat-max>: maximum repeatition forces --repeat"
+	echo -e "	--repeat-min <repeat-min>: minimum repeatition forces repeat [default: ' 1 ']"
+	echo -e "	--repeat-max <repeat-max>: maximum repeatition forces repeat"
 	echo -e "	--one-of <one-of>: accepted values, repeatable"
-	echo -e "	--subcommand-directory <subcommand-directory>: directory containing subcommands, force subcommand, list parseArger script in directory to fill --one-of"
-	echo -e "	--subcommand-variable <subcommand-variable>: array variable containing subcommand parts, force subcommand [default: ' __subcommand ']"
+	echo -e "	-d, --default-value <default-value>: value, repeatable"
+	echo -e "	-s, --short <short>: short form"
+	echo -e "	--alias <alias>: option alias, repeatable"
+	echo -e "	--empty-value <empty-value>: value for empty option"
 	echo -e "	--complete <complete>: bash built-in completely function, repeatable"
 	echo -e "	--complete-custom <complete-custom>: completely custom dynamic suggestion, repeatable"
+	echo -e "	--env <env>: environment variable name"
 	echo -e "	--match <match>: regex match validation"
-	echo -e "	--subcommand-run|--no-subcommand-run: run subcommand, forces sub command"
 	echo -e "	-r|--repeat|--no-repeat: repeatable"
-	echo -e "	--optional|--no-optional: optional"
-	echo -e "	--subcommand|--no-subcommand: is a subcommand"
-	echo -e "	--subcommand-use-leftovers|--no-subcommand-use-leftovers: add leftover arguments to subcommand, forces subcommand"
+	echo -e "	--empty|--no-empty: use option as flag"
+	echo -e "	-q|--required|--no-required: make option mandatory"
 	echo -e "Usage :
-	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--subcommand-directory <value>] [--subcommand-variable <value>] [--complete <value>] [--complete-custom <value>] [--match <value>] [--[no-]subcommand-run] [--[no-]repeat] [--[no-]optional] [--[no-]subcommand] [--[no-]subcommand-use-leftovers]";
+	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--default-value <value>] [--short <value>] [--alias <value>] [--empty-value <value>] [--complete <value>] [--complete-custom <value>] [--env <value>] [--match <value>] [--[no-]repeat] [--[no-]empty] [--[no-]required]";
 	fi
 
 }
@@ -183,22 +178,46 @@ parse_commandline()
 				_arg_one_of+=("${_key##--one-of=}")
 				;;
 			
-			--subcommand-directory)
+			-d|--default-value)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_subcommand_directory="$2"
+				_arg_default_value+=("$2")
 				shift
 				;;
-			--subcommand-directory=*)
-				_arg_subcommand_directory="${_key##--subcommand-directory=}"
+			--default-value=*)
+				_arg_default_value+=("${_key##--default-value=}")
+				;;
+			-d*)
+				_arg_default_value+=("${_key##-d}")
 				;;
 			
-			--subcommand-variable)
+			-s|--short)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_subcommand_variable="$2"
+				_arg_short="$2"
 				shift
 				;;
-			--subcommand-variable=*)
-				_arg_subcommand_variable="${_key##--subcommand-variable=}"
+			--short=*)
+				_arg_short="${_key##--short=}"
+				;;
+			-s*)
+				_arg_short="${_key##-s}"
+				;;
+			
+			--alias)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_alias+=("$2")
+				shift
+				;;
+			--alias=*)
+				_arg_alias+=("${_key##--alias=}")
+				;;
+			
+			--empty-value)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_empty_value="$2"
+				shift
+				;;
+			--empty-value=*)
+				_arg_empty_value="${_key##--empty-value=}"
 				;;
 			
 			--complete)
@@ -219,6 +238,15 @@ parse_commandline()
 				_arg_complete_custom+=("${_key##--complete-custom=}")
 				;;
 			
+			--env)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_env="$2"
+				shift
+				;;
+			--env=*)
+				_arg_env="${_key##--env=}"
+				;;
+			
 			--match)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_match="$2"
@@ -228,35 +256,23 @@ parse_commandline()
 				_arg_match="${_key##--match=}"
 				;;
 			
-			--subcommand-run)
-				_arg_subcommand_run="on"
-				;;
-			--no-subcommand-run)
-				_arg_subcommand_run="off"
-				;;
 			-r|--repeat)
 				_arg_repeat="on"
 				;;
 			--no-repeat)
 				_arg_repeat="off"
 				;;
-			--optional)
-				_arg_optional="on"
+			--empty)
+				_arg_empty="on"
 				;;
-			--no-optional)
-				_arg_optional="off"
+			--no-empty)
+				_arg_empty="off"
 				;;
-			--subcommand)
-				_arg_subcommand="on"
+			-q|--required)
+				_arg_required="on"
 				;;
-			--no-subcommand)
-				_arg_subcommand="off"
-				;;
-			--subcommand-use-leftovers)
-				_arg_subcommand_use_leftovers="on"
-				;;
-			--no-subcommand-use-leftovers)
-				_arg_subcommand_use_leftovers="off"
+			--no-required)
+				_arg_required="off"
 				;;
 			-h|--help)
 				print_help;
@@ -291,18 +307,6 @@ parse_commandline()
 					fi
 					;;
 				
-				# parsing leftovers
-				--*)
-					if [[ "$2" =~ ^--([^=]+)(=(.*))?$ ]] || [ "$2" = "" ]; then
-						_arg_parsed_leftovers["${1#--}"]="on"
-					elif [[ "$1" =~ ^--([^=]+)=(.*)$ ]]; then
-						_arg_parsed_leftovers["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}";
-					else
-						_arg_parsed_leftovers["${1#--}"]="${2}";
-						shift;
-					fi
-					;;
-
 				*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -338,7 +342,11 @@ assign_positional_args()
 		test $# -gt 0 || break;
 		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
 			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
-			eval "local _regex=\$(eval \"echo \\\"\\\$_match\${_positional_name}\\\"\");if [ \"\$_regex\" != \"\" ];then [[ \"\${1}\" =~ \$_regex ]] || die \"\${_positional_name} does not match pattern: \$_regex\";fi";
+			local _match_var="_match${_positional_name}";
+			local _regex="${!_match_var}";
+			if [ -n "$_regex" ]; then
+				[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
+			fi
 		fi
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
@@ -356,16 +364,17 @@ print_debug()
 	echo -e "	repeat-min: ${_arg_repeat_min}";
 	echo -e "	repeat-max: ${_arg_repeat_max}";
 	echo -e "	one-of: ${_arg_one_of[*]}";
-	echo -e "	subcommand-directory: ${_arg_subcommand_directory}";
-	echo -e "	subcommand-variable: ${_arg_subcommand_variable}";
+	echo -e "	default-value: ${_arg_default_value[*]}";
+	echo -e "	short: ${_arg_short}";
+	echo -e "	alias: ${_arg_alias[*]}";
+	echo -e "	empty-value: ${_arg_empty_value}";
 	echo -e "	complete: ${_arg_complete[*]}";
 	echo -e "	complete-custom: ${_arg_complete_custom[*]}";
+	echo -e "	env: ${_arg_env}";
 	echo -e "	match: ${_arg_match}";
-	echo -e "	subcommand-run: ${_arg_subcommand_run}";
 	echo -e "	repeat: ${_arg_repeat}";
-	echo -e "	optional: ${_arg_optional}";
-	echo -e "	subcommand: ${_arg_subcommand}";
-	echo -e "	subcommand-use-leftovers: ${_arg_subcommand_use_leftovers}";
+	echo -e "	empty: ${_arg_empty}";
+	echo -e "	required: ${_arg_required}";
 	echo -e "	leftovers: ${_arg_leftovers[*]}";
 
 }
@@ -387,59 +396,6 @@ trap on_interrupt INT;
 # print_debug "$@"
 # @parseArger-end
 
-SCRIPT_ROOT_DIR="$(
-  cd "$(dirname "${BASH_SOURCE[0]}")"
-  pwd -P
-)/..";
-
-# shellcheck source=../utils
-source "${SCRIPT_ROOT_DIR}/utils";
-
-initStr="_arg_${_arg_arg_name//-/_}=\"$_arg_default_value\";";
-
-if [ "$_arg_subcommand_directory" != "" ]; then
-	if [ -d "$_arg_subcommand_directory" ]; then
-		_arg_subcommand="on";
-		for file in "$_arg_subcommand_directory/"*; do
-			tname="$(basename "$file")";
-			if ! [[ "${_arg_one_of[*]}" =~ " $tname " ]] && [ -f "$file" ] && parsearger_is_pa_file "$file"; then
-				_arg_one_of+=("$tname");
-			fi
-		done
-	fi
+if [ "$_arg_required" == "on" ]; then
+    echo "if [ -z \"\$_arg_${_arg_arg_name//-/_}\" ]; then die \"Missing required option: ${_arg_arg_name}\"; fi;"
 fi
-
-if [ "${#_arg_one_of[@]}" -gt 0 ]; then
-	initStr+="\n_one_of_arg_${_arg_arg_name//-/_}=(";
-	for i in "${_arg_one_of[@]}"; do
-		initStr+="\"$i\" ";
-	done
-	initStr+=");";
-fi
-
-if [ "$_arg_optional" == "on" ]; then
-	initStr+="\n_optional_positionals+=(\"_arg_${_arg_arg_name//-/_}\");";
-fi
-
-if [ "$_arg_subcommand_run" != "off" ]; then
-	_arg_subcommand="on";
-fi
-
-if [ "$_arg_subcommand_use_leftovers" != "off" ]; then
-	_arg_subcommand="on";
-fi
-
-if [ "$_arg_subcommand_variable" != "__subcommand" ]; then
-	_arg_subcommand="on";
-fi
-
-if [ "$_arg_subcommand" == "on" ]; then
-	initStr+="\n_arg_subcommand_arg=\"_arg_${_arg_arg_name//-/_}\";";
-	initStr+="\n${_arg_subcommand_variable}=();";
-fi
-
-if [ "$_arg_match" != "" ]; then
-    initStr+="\n_match_arg_${_arg_arg_name//-/_}=\"${_arg_match}\";";
-fi
-
-echo -e "$initStr";
diff --git a/bin/opt/init b/bin/opt/init
--- a/bin/opt/init
+++ b/bin/opt/init
@@ -2,7 +2,15 @@
 # @parseArger-begin
 # @parseArger-help "parseArger init string for options" --option "help" --short-option "h"
 # @parseArger-version "0.1" --option "version" --short-option "v"
-# @parseArger-verbose --option "verbose" --level "0"
+# @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
+# @parseArger-leftovers leftovers --parse
+_has_colors=0
+if [ -t 1 ]; then # Check if stdout is a terminal
+	ncolors=$(tput colors 2>/dev/null)
+	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+		_has_colors=1
+	fi
+fi
 # @parseArger-declarations
 # @parseArger pos arg-name "positional argument name"
 # @parseArger pos description "positional argument description"
@@ -15,8 +23,11 @@
 # @parseArger opt empty-value "value for empty option"
 # @parseArger opt complete "bash built-in completely function" --repeat
 # @parseArger opt complete-custom "completely custom dynamic suggestion" --repeat
+# @parseArger opt env "environment variable name"
+# @parseArger opt match "regex match validation"
 # @parseArger flag repeat "repeatable" --short r
 # @parseArger flag empty "use option as flag"
+# @parseArger flag required "make option mandatory" --short q
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -25,9 +36,15 @@ _SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
+
+__cli_arg_count=$#;
+
 die()
 {
-	local _ret="${2:-1}"
+	local _ret=1
+    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+   	_ret="$2"
+    fi
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	log "$1" -3 >&2
 	exit "${_ret}"
@@ -43,6 +60,7 @@ begins_with_short_option()
 
 # POSITIONALS ARGUMENTS
 _positionals=();
+_optional_positionals=();
 _arg_arg_name="";
 _arg_description="";
 # OPTIONALS ARGUMENTS
@@ -55,9 +73,17 @@ _arg_alias=()
 _arg_empty_value=
 _arg_complete=()
 _arg_complete_custom=()
+_arg_env=
+_arg_match=
 # FLAGS
 _arg_repeat="off"
 _arg_empty="off"
+_arg_required="off"
+# NESTED
+# LEFTOVERS
+_arg_leftovers=()
+# LEFTOVERS
+	declare -A _arg_parsed_leftovers
 _verbose_level="0";
 
 
@@ -80,17 +106,20 @@ print_help()
 	echo -e "	--empty-value <empty-value>: value for empty option"
 	echo -e "	--complete <complete>: bash built-in completely function, repeatable"
 	echo -e "	--complete-custom <complete-custom>: completely custom dynamic suggestion, repeatable"
+	echo -e "	--env <env>: environment variable name"
+	echo -e "	--match <match>: regex match validation"
 	echo -e "	-r|--repeat|--no-repeat: repeatable"
 	echo -e "	--empty|--no-empty: use option as flag"
+	echo -e "	-q|--required|--no-required: make option mandatory"
 	echo -e "Usage :
-	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--default-value <value>] [--short <value>] [--alias <value>] [--empty-value <value>] [--complete <value>] [--complete-custom <value>] [--[no-]repeat] [--[no-]empty]";
+	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--default-value <value>] [--short <value>] [--alias <value>] [--empty-value <value>] [--complete <value>] [--complete-custom <value>] [--env <value>] [--match <value>] [--[no-]repeat] [--[no-]empty] [--[no-]required]";
 	fi
 
 }
 
 log() {
 	local _arg_msg="${1}";
-	local _arg_level="${2:0}";
+	local _arg_level="${2:-0}";
 	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
 		case "$_arg_level" in
 			-3)
@@ -115,7 +144,11 @@ log() {
 				_arg_COLOR="\033[0m";
 				;;
 		esac
-		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+		if [ "${_has_colors}" == "1" ]; then
+			echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+		else
+			echo "${_arg_msg}";
+		fi
 	fi
 }
 
@@ -213,6 +246,24 @@ parse_commandline()
 				_arg_complete_custom+=("${_key##--complete-custom=}")
 				;;
 			
+			--env)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_env="$2"
+				shift
+				;;
+			--env=*)
+				_arg_env="${_key##--env=}"
+				;;
+			
+			--match)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_match="$2"
+				shift
+				;;
+			--match=*)
+				_arg_match="${_key##--match=}"
+				;;
+			
 			-r|--repeat)
 				_arg_repeat="on"
 				;;
@@ -225,6 +276,12 @@ parse_commandline()
 			--no-empty)
 				_arg_empty="off"
 				;;
+			-q|--required)
+				_arg_required="on"
+				;;
+			--no-required)
+				_arg_required="off"
+				;;
 			-h|--help)
 				print_help;
 				exit 0;
@@ -233,24 +290,36 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
-			-v|--version)
-				print_version;
-				exit 0;
-				;;
-			-v*)
-				print_version;
-				exit 0;
-				;;
 			--verbose)
-				if [ $# -lt 2 ];then
-					_verbose_level="$((_verbose_level + 1))";
-				else
-					_verbose_level="$2";
-					shift;
-				fi
-				;;
-			
-			*)
+					if [ $# -lt 2 ];then
+						_verbose_level="$((_verbose_level + 1))";
+					else
+						_verbose_level="$2";
+						shift;
+					fi
+					;;
+				--quiet)
+					if [ $# -lt 2 ];then
+						_verbose_level="$((_verbose_level - 1))";
+					else
+						_verbose_level="-$2";
+						shift;
+					fi
+					;;
+				
+				# parsing leftovers
+				--*)
+					if [[ "$2" =~ ^--([^=]+)(=(.*))?$ ]] || [ "$2" = "" ]; then
+						_arg_parsed_leftovers["${1#--}"]="on"
+					elif [[ "$1" =~ ^--([^=]+)=(.*)$ ]]; then
+						_arg_parsed_leftovers["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}";
+					else
+						_arg_parsed_leftovers["${1#--}"]="${2}";
+						shift;
+					fi
+					;;
+
+				*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
 				_positionals_count=$((_positionals_count + 1))
@@ -264,9 +333,6 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="arg-name description"
-	if [ "${_positionals_count}" -gt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
-		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
-	fi
 	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
 		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}.
 	${_positionals[*]}" 1;
@@ -278,10 +344,18 @@ assign_positional_args()
 {
 	local _positional_name _shift_for=$1;
 	_positional_names="_arg_arg_name _arg_description ";
+	_leftovers_count=$((${#_positionals[@]} - 2))
+	for ((ii = 0; ii < _leftovers_count; ii++));do
+		_positional_names="$_positional_names _arg_leftovers[$((ii + 0))]";
+	done
+
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		if ! [[ "$_positional_name" =~ "_arg_leftovers" ]];then
+			eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+			eval "local _regex=\$(eval \"echo \\\"\\\$_match\${_positional_name}\\\"\");if [ \"\$_regex\" != \"\" ];then [[ \"\${1}\" =~ \$_regex ]] || die \\\"\\\${_positional_name} does not match pattern: \$_regex\\\";fi";
+		fi
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
@@ -293,30 +367,31 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "\targ-name: ${_arg_arg_name}";
-	echo -e "\tdescription: ${_arg_description}";
-	echo -e "\trepeat-min: ${_arg_repeat_min}";
-	echo -e "\trepeat-max: ${_arg_repeat_max}";
-	echo -e "\tone-of: ${_arg_one_of[*]}";
-	echo -e "\tdefault-value: ${_arg_default_value[*]}";
-	echo -e "\tshort: ${_arg_short}";
-	echo -e "\talias: ${_arg_alias[*]}";
-	echo -e "\tempty-value: ${_arg_empty_value}";
-	echo -e "\tcomplete: ${_arg_complete[*]}";
-	echo -e "\tcomplete-custom: ${_arg_complete_custom[*]}";
-	echo -e "\trepeat: ${_arg_repeat}";
-	echo -e "\tempty: ${_arg_empty}";
+	echo -e "	arg-name: ${_arg_arg_name}";
+	echo -e "	description: ${_arg_description}";
+	echo -e "	repeat-min: ${_arg_repeat_min}";
+	echo -e "	repeat-max: ${_arg_repeat_max}";
+	echo -e "	one-of: ${_arg_one_of[*]}";
+	echo -e "	default-value: ${_arg_default_value[*]}";
+	echo -e "	short: ${_arg_short}";
+	echo -e "	alias: ${_arg_alias[*]}";
+	echo -e "	empty-value: ${_arg_empty_value}";
+	echo -e "	complete: ${_arg_complete[*]}";
+	echo -e "	complete-custom: ${_arg_complete_custom[*]}";
+	echo -e "	env: ${_arg_env}";
+	echo -e "	match: ${_arg_match}";
+	echo -e "	repeat: ${_arg_repeat}";
+	echo -e "	empty: ${_arg_empty}";
+	echo -e "	required: ${_arg_required}";
+	echo -e "	leftovers: ${_arg_leftovers[*]}";
 
 }
 
-print_version()
-{
-	echo "0.1";
-}
 
 on_interrupt() {
 	die Process aborted! 130;
 }
+
 
 parse_commandline "$@";
 handle_passed_args_count;
@@ -329,36 +404,60 @@ trap on_interrupt INT;
 # print_debug "$@"
 # @parseArger-end
 
-if [ "$_arg_repeat_min" -gt "1" ] || [ "$_arg_repeat_max" != "" ]; then
-	_arg_repeat="on";
-fi
-
 _arg_arg_name="${_arg_arg_name//-/_}"
 outStr="_arg_${_arg_arg_name}=";
 
-if [ "$_arg_repeat" != "off" ]; then
-    outStr+="(";
-fi
-
+# Handle --env
+default_val_str=""
 if [ "${#_arg_default_value[@]}" -gt 0 ]; then
     if [ "$_arg_repeat" == "off" ]; then
-        outStr+="\"${_arg_default_value[*]}\"";
+        default_val_str="${_arg_default_value[*]}";
     else
-        for idfv in "${_arg_default_value[@]}"; do
-            outStr+="\"$idfv\" ";
-        done
+        # For arrays with default values, we just init the array.
+        # Env vars for arrays are tricky, let's skip env for arrays for now or handle simple cases.
+        # If env is set, we might want to split it? Too complex for now.
+        :
     fi
 fi
 
-if [ "$_arg_repeat" != "off" ]; then
-    outStr+=")";
+if [ "$_arg_env" != "" ] && [ "$_arg_repeat" == "off" ]; then
+    # if env var is set, use it, else use default
+    if [ "$default_val_str" != "" ]; then
+        outStr+="\"\${${_arg_env}:-$default_val_str}\"";
+    else
+        outStr+="\"\${${_arg_env}}\"";
+    fi
+else
+    # Existing logic
+    if [ "$_arg_repeat" != "off" ]; then
+        outStr+="(";
+    fi
+
+    if [ "${#_arg_default_value[@]}" -gt 0 ]; then
+        if [ "$_arg_repeat" == "off" ]; then
+            outStr+="\"${_arg_default_value[*]}\"";
+        else
+            for idfv in "${_arg_default_value[@]}"; do
+                outStr+="\"$idfv\" ";
+            done
+        fi
+    fi
+
+    if [ "$_arg_repeat" != "off" ]; then
+        outStr+=")";
+    fi
 fi
+
 if [ "${#_arg_one_of[@]}" -gt 0 ]; then
     outStr+="\n_one_of_arg_${_arg_arg_name//-/_}=(";
     for i in "${_arg_one_of[@]}"; do
         outStr+="\"$i\" ";
     done
     outStr+=");";
+fi
+
+if [ "$_arg_required" == "on" ]; then
+    outStr+="\n_required_arg_${_arg_arg_name//-/_}=\"on\";";
 fi
 
 echo -e "$outStr";
diff --git a/bin/parse b/bin/parse
--- a/bin/parse
+++ b/bin/parse
@@ -1,21 +1,29 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "parse an existing parseArger file" --option "help" --short-option "h"
-# @parseArger-version "0.1" --option "version" --short-option "v"
+# @parseArger-help "parse an existing parseArger script and add arguments, options, flag, etc..." --option "help" --short-option "h"
 # @parseArger-verbose --option "verbose" --level "0" --quiet-option "quiet"
+# @parseArger-set export PARSEARGER_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/..;pwd -P);
+export PARSEARGER_ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/..;pwd -P);
+_has_colors=0
+if [ -t 1 ]; then # Check if stdout is a terminal
+	ncolors=$(tput colors 2>/dev/null)
+	if [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
+		_has_colors=1
+	fi
+fi
 # @parseArger-declarations
-# @parseArger pos file "file to parse" --complete "file"
+# @parseArger pos file "file to parse"
 # @parseArger opt pos "add positional argument declaration" --short p --repeat
 # @parseArger opt opt "add optional arg declaration" --short o --repeat
 # @parseArger opt flag "add flag declaration" --short f --repeat
-# @parseArger opt nested "add nested option declaration" --repeat
 # @parseArger opt set "add declare var" --short s --repeat
 # @parseArger opt source "add file to source" --short l --repeat
 # @parseArger opt set-version "set version"
-# @parseArger opt dependencies "specify script dependencies" --repeat
+# @parseArger opt dependencies "set a dependency" --repeat
+# @parseArger opt nested "nested option declaration" --repeat
 # @parseArger flag inplace "replace parseArger generated content in place" --short i
-# @parseArger flag leftovers "add leftovers"
-# @parseArger flag parse-leftovers "parse leftovers"
+# @parseArger flag leftovers "enable leftovers"
+# @parseArger flag parse-leftovers "enable parsing of leftovers"
 # @parseArger-declarations-end
 
 # @parseArger-utils
@@ -24,9 +32,15 @@ _SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
 # @parseArger-utils-end
 
 # @parseArger-parsing
+
+__cli_arg_count=$#;
+
 die()
 {
-	local _ret="${2:-1}"
+	local _ret=1
+    if [[ -n "$2" ]] && [[ "$2" =~ ^[0-9]+$ ]]; then
+   	_ret="$2"
+    fi
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	log "$1" -3 >&2
 	exit "${_ret}"
@@ -48,15 +62,16 @@ _arg_file="";
 _arg_pos=()
 _arg_opt=()
 _arg_flag=()
-_arg_nested=()
 _arg_set=()
 _arg_source=()
 _arg_set_version=
 _arg_dependencies=()
+_arg_nested=()
 # FLAGS
 _arg_inplace="off"
 _arg_leftovers="off"
 _arg_parse_leftovers="off"
+# NESTED
 _verbose_level="0";
 
 
@@ -67,28 +82,28 @@ print_help()
 
 	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
 		_helpHasBeenPrinted=0;
-		echo -e "parse an existing parseArger file:"
+		echo -e "parse an existing parseArger script and add arguments, options, flag, etc...:"
 	echo -e "	file: file to parse"
 	echo -e "	-p, --pos <pos>: add positional argument declaration, repeatable"
 	echo -e "	-o, --opt <opt>: add optional arg declaration, repeatable"
 	echo -e "	-f, --flag <flag>: add flag declaration, repeatable"
-	echo -e "	--nested <nested>: add nested option declaration, repeatable"
 	echo -e "	-s, --set <set>: add declare var, repeatable"
 	echo -e "	-l, --source <source>: add file to source, repeatable"
 	echo -e "	--set-version <set-version>: set version"
-	echo -e "	--dependencies <dependencies>: script dependencies, repeatable"
+	echo -e "	--dependencies <dependencies>: set a dependency, repeatable"
+	echo -e "	--nested <nested>: nested option declaration, repeatable"
 	echo -e "	-i|--inplace|--no-inplace: replace parseArger generated content in place"
-	echo -e "	--leftovers|--no-leftovers: add leftovers"
-	echo -e "	--parse-leftovers|--no-parse-leftovers: parse leftovers"
+	echo -e "	--leftovers|--no-leftovers: enable leftovers"
+	echo -e "	--parse-leftovers|--no-parse-leftovers: enable parsing of leftovers"
 	echo -e "Usage :
-	$0 <file> [--pos <value>] [--opt <value>] [--flag <value>] [--nested <value>] [--set <value>] [--source <value>] [--set-version <value>] [--[no-]inplace] [--[no-]leftovers] [--[no-]parse-leftovers]";
+	$0 <file> [--pos <value>] [--opt <value>] [--flag <value>] [--set <value>] [--source <value>] [--set-version <value>] [--dependencies <value>] [--nested <value>] [--[no-]inplace] [--[no-]leftovers] [--[no-]parse-leftovers]";
 	fi
 
 }
 
 log() {
 	local _arg_msg="${1}";
-	local _arg_level="${2:-"0"}";
+	local _arg_level="${2:-0}";
 	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
 		case "$_arg_level" in
 			-3)
@@ -113,7 +128,11 @@ log() {
 				_arg_COLOR="\033[0m";
 				;;
 		esac
-		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+		if [ "${_has_colors}" == "1" ]; then
+			echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+		else
+			echo "${_arg_msg}";
+		fi
 	fi
 }
 
@@ -159,15 +178,6 @@ parse_commandline()
 			-f*)
 				_arg_flag+=("${_key##-f}")
 				;;
-
-			--nested)
-				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
-				_arg_nested+=("$2")
-				shift
-				;;
-			--nested=*)
-				_arg_nested+=("${_key##--nested=}")
-				;;
 			
 			-s|--set)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
@@ -201,6 +211,7 @@ parse_commandline()
 			--set-version=*)
 				_arg_set_version="${_key##--set-version=}"
 				;;
+			
 			--dependencies)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_dependencies+=("$2")
@@ -208,6 +219,15 @@ parse_commandline()
 				;;
 			--dependencies=*)
 				_arg_dependencies+=("${_key##--dependencies=}")
+				;;
+			
+			--nested)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_nested+=("$2")
+				shift
+				;;
+			--nested=*)
+				_arg_nested+=("${_key##--nested=}")
 				;;
 			
 			-i|--inplace)
@@ -234,14 +254,6 @@ parse_commandline()
 				;;
 			-h*)
 				print_help;
-				exit 0;
-				;;
-			-v|--version)
-				print_version;
-				exit 0;
-				;;
-			-v*)
-				print_version;
 				exit 0;
 				;;
 			--verbose)
@@ -293,6 +305,11 @@ assign_positional_args()
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
 		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		local _match_var="_match${_positional_name}"
+		local _regex="${!_match_var}"
+		if [ -n "$_regex" ]; then
+			[[ "${1}" =~ $_regex ]] || die "${_positional_name} does not match pattern: $_regex"
+		fi
 		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
@@ -304,29 +321,26 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "\tfile: ${_arg_file}";
-	echo -e "\tpos: ${_arg_pos[*]}";
-	echo -e "\topt: ${_arg_opt[*]}";
-	echo -e "\tflag: ${_arg_flag[*]}";
-	echo -e "\tnested: ${_arg_nested[*]}";
-	echo -e "\tset: ${_arg_set[*]}";
-	echo -e "\tsource: ${_arg_source[*]}";
-	echo -e "\tset-version: ${_arg_set_version}";
-	echo -e "\tdependencies: ${_arg_dependencies[*]}";
-	echo -e "\tinplace: ${_arg_inplace}";
-	echo -e "\tleftovers: ${_arg_leftovers}";
-	echo -e "\tparse-leftovers: ${_arg_parse_leftovers}";
+	echo -e "	file: ${_arg_file}";
+	echo -e "	pos: ${_arg_pos[*]}";
+	echo -e "	opt: ${_arg_opt[*]}";
+	echo -e "	flag: ${_arg_flag[*]}";
+	echo -e "	set: ${_arg_set[*]}";
+	echo -e "	source: ${_arg_source[*]}";
+	echo -e "	set-version: ${_arg_set_version}";
+	echo -e "	dependencies: ${_arg_dependencies[*]}";
+	echo -e "	nested: ${_arg_nested[*]}";
+	echo -e "	inplace: ${_arg_inplace}";
+	echo -e "	leftovers: ${_arg_leftovers}";
+	echo -e "	parse-leftovers: ${_arg_parse_leftovers}";
 
 }
 
-print_version()
-{
-	echo "0.1";
-}
 
 on_interrupt() {
 	die Process aborted! 130;
 }
+
 
 parse_commandline "$@";
 handle_passed_args_count;
@@ -338,7 +352,6 @@ trap on_interrupt INT;
 # @parseArger-parsing-end
 # print_debug "$@"
 # @parseArger-end
-
 SCRIPT_ROOT_DIR=$(
   cd "$(dirname "${BASH_SOURCE[0]}")"
   pwd -P
