bin/opt/* use parseArger

diff --git a/bin/opt/docopt-help b/bin/opt/docopt-help
--- a/bin/opt/docopt-help
+++ b/bin/opt/docopt-help
@@ -1,24 +1,22 @@
 #!/bin/bash
+# @parseArger-begin
+# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-declarations
+# @parseArger pos arg-name "positional argument name"
+# @parseArger pos description "positional argument description"
+# @parseArger opt repeat-min "minimum repeatition forces repeat" --default-value "1"
+# @parseArger opt repeat-max "maximum repeatition forces repeat"
+# @parseArger opt one-of "accepted values" --repeat
+# @parseArger opt default-value "value" --short d --repeat
+# @parseArger opt short "short form" --short s
+# @parseArger flag repeat "repeatable" --short r
+# @parseArger-declarations-end
 
-# Created by argbash-init v2.10.0
-# ARG_OPTIONAL_SINGLE([short],[s],[short option])
-# ARG_OPTIONAL_SINGLE([template])
-# ARG_OPTIONAL_SINGLE([default-value],[d],[default value])
-# ARG_OPTIONAL_BOOLEAN([repeat],[r],[repeatable])
-# ARG_OPTIONAL_REPEATED([one-of],[],[list of accepted values])
-# ARG_POSITIONAL_SINGLE([arg-name],[positional argument name])
-# ARG_POSITIONAL_SINGLE([description],[positional argument description])
-# ARG_OPTIONAL_BOOLEAN([empty],[],[value can be empty])
-# ARG_OPTIONAL_SINGLE([empty-value],[],[value when empty, force --empty])
-# ARG_DEFAULTS_POS([])
-# ARG_HELP([<generate the parseArg parseable string for positional argument>])
-# ARGBASH_GO()
-# needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
-# Argbash is a bash code generator used to get arguments parsing right.
-# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+# @parseArger-utils-end
 
-
+# @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
@@ -30,38 +28,44 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='sdrh'
+	local first_option all_short_options=''
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
-# THE DEFAULTS INITIALIZATION - POSITIONALS
-_positionals=()
-_arg_arg_name=
-_arg_description=
-# THE DEFAULTS INITIALIZATION - OPTIONALS
+# POSITIONALS ARGUMENTS
+_positionals=();
+_arg_arg_name="";
+_arg_description="";
+# OPTIONALS ARGUMENTS
+_arg_repeat_min="1"
+_arg_repeat_max=
+_arg_one_of=()
+_arg_default_value=()
 _arg_short=
-_arg_template=
-_arg_default_value=
+# FLAGS
 _arg_repeat="off"
-_arg_empty="off"
-_arg_empty_value=
 
 
 print_help()
 {
-	printf '%s\n' "<generate the parseArg parseable string for positional argument>"
-	printf 'Usage: %s [-s|--short <arg>] [--template <arg>] [-d|--default-value <arg>] [-r|--(no-)repeat] [--(no-)empty] [--empty-value <arg>] [-h|--help] <arg-name> <description>\n' "$0"
-	printf '\t%s\n' "<arg-name>: positional argument name"
-	printf '\t%s\n' "<description>: positional argument description"
-	printf '\t%s\n' "-s, --short: short option (no default)"
-	printf '\t%s\n' "-d, --default-value: default value (no default)"
-	printf '\t%s\n' "-r, --repeat, --no-repeat: repeatable (off by default)"
-	printf '\t%s\n' "--empty, --no-empty: value can be empty (off by default)"
-	printf '\t%s\n' "--empty-value: value when empty, force --empty (no default)"
-	printf '\t%s\n' "-h, --help: Prints help"
-}
 
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "I send an SOS to the world:"
+	echo -e "	arg-name: positional argument name"
+	echo -e "	description: positional argument description"
+	echo -e "	--repeat-min <repeat-min>: minimum repeatition forces repeat [default: ' 1 ']"
+	echo -e "	--repeat-max <repeat-max>: maximum repeatition forces repeat"
+	echo -e "	--one-of <one-of>: accepted values, repeatable"
+	echo -e "	-d, --default-value <default-value>: value, repeatable"
+	echo -e "	-s, --short <short>: short form"
+	echo -e "	-r|--repeat|--no-repeat: repeatable"
+	echo -e "Usage :
+	$0 <arg-name> <description> [--repeat-min <value>] [--repeat-max <value>] [--one-of <value>] [--default-value <value>] [--short <value>] [--[no-]repeat]";
+	fi
+
+}
 
 parse_commandline()
 {
@@ -70,8 +74,47 @@ parse_commandline()
 	do
 		_key="$1"
 		case "$_key" in
+			--repeat-min)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_repeat_min="$2"
+				shift
+				;;
+			--repeat-min=*)
+				_arg_repeat_min="${_key##--repeat-min=}"
+				;;
+			
+			--repeat-max)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_repeat_max="$2"
+				shift
+				;;
+			--repeat-max=*)
+				_arg_repeat_max="${_key##--repeat-max=}"
+				;;
+			
+			--one-of)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_one_of+=("$2")
+				shift
+				;;
+			--one-of=*)
+				_arg_one_of+=("${_key##--one-of=}")
+				;;
+			
+			-d|--default-value)
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
+				_arg_default_value+=("$2")
+				shift
+				;;
+			--default-value=*)
+				_arg_default_value+=("${_key##--default-value=}")
+				;;
+			-d*)
+				_arg_default_value+=("${_key##-d}")
+				;;
+			
 			-s|--short)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_short="$2"
 				shift
 				;;
@@ -81,56 +124,18 @@ parse_commandline()
 			-s*)
 				_arg_short="${_key##-s}"
 				;;
-			--template)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_template="$2"
-				shift
-				;;
-			--template=*)
-				_arg_template="${_key##--template=}"
-				;;
-			-d|--default-value)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_default_value="$2"
-				shift
-				;;
-			--default-value=*)
-				_arg_default_value="${_key##--default-value=}"
-				;;
-			-d*)
-				_arg_default_value="${_key##-d}"
-				;;
+			
 			-r|--no-repeat|--repeat)
 				_arg_repeat="on"
 				test "${1:0:5}" = "--no-" && _arg_repeat="off"
 				;;
-			-r*)
-				_arg_repeat="on"
-				_next="${_key##-r}"
-				if test -n "$_next" -a "$_next" != "$_key"
-				then
-					{ begins_with_short_option "$_next" && shift && set -- "-r" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
-				fi
-				;;
-			--no-empty|--empty)
-				_arg_empty="on"
-				test "${1:0:5}" = "--no-" && _arg_empty="off"
-				;;
-			--empty-value)
-				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_empty_value="$2"
-				shift
-				;;
-			--empty-value=*)
-				_arg_empty_value="${_key##--empty-value=}"
-				;;
 			-h|--help)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			-h*)
-				print_help
-				exit 0
+				print_help;
+				exit 0;
 				;;
 			*)
 				_last_positional="$1"
@@ -145,37 +150,60 @@ parse_commandline()
 
 handle_passed_args_count()
 {
-	local _required_args_string="'arg-name' and 'description'"
-	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+	local _required_args_string="arg-name description"
+	if [ "${_positionals_count}" -lt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+	fi
+	if [ "${_positionals_count}" -gt 2 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1;
+	fi
 }
 
 
 assign_positional_args()
 {
-	local _positional_name _shift_for=$1
-	_positional_names="_arg_arg_name _arg_description "
-
+	local _positional_name _shift_for=$1;
+	_positional_names="_arg_arg_name _arg_description ";
 	shift "$_shift_for"
-	for _positional_name in ${_positional_names}
-	do
-		test $# -gt 0 || break
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-		shift
+	for _positional_name in ${_positional_names};do
+		test $# -gt 0 || break;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		shift;
 	done
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_debug()
+{
+	print_help
+	# shellcheck disable=SC2145
+	echo "DEBUG: $0 $@";
+	
+	echo -e "\targ-name: ${_arg_arg_name}";
+	echo -e "\tdescription: ${_arg_description}";
+	echo -e "\trepeat-min: ${_arg_repeat-min | sed 's/-/_/g'}";
+	echo -e "\trepeat-max: ${_arg_repeat-max | sed 's/-/_/g'}";
+	echo -e "\tone-of: ${_arg_one-of | sed 's/-/_/g'}";
+	echo -e "\tdefault-value: ${_arg_default-value | sed 's/-/_/g'}";
+	echo -e "\tshort: ${_arg_short | sed 's/-/_/g'}";
+	echo -e "\trepeat: ${_arg_repeat | sed 's/-/_/g'}";
 
-# OTHER STUFF GENERATED BY Argbash
+}
 
-### END OF CODE GENERATED BY Argbash (sortof) ### ])
-# [ <-- needed because of Argbash
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
 
 
-# vvv  PLACE YOUR CODE HERE  vvv
+# @parseArger-parsing-end
+# print_debug "$@"
+# @parseArger-end
+
 optHelp="--${_arg_arg_name} ${_arg_arg_name}";
 
 if [ "$_arg_short" != "" ]; then
@@ -189,7 +217,3 @@ if [ "$_arg_default_value" != "" ]; then
 fi
 
 echo -e "${optHelp}";
-
-# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^
-
-# ] <-- needed because of Argbash
