--one-of for pos and opt

diff --git a/bin/opt/parser b/bin/opt/parser
--- a/bin/opt/parser
+++ b/bin/opt/parser
@@ -5,6 +5,7 @@
 # ARG_OPTIONAL_SINGLE([template])
 # ARG_OPTIONAL_SINGLE([default-value],[d],[default value])
 # ARG_OPTIONAL_BOOLEAN([repeat],[r],[repeatable])
+# ARG_OPTIONAL_REPEATED([one-of],[],[list of accepted values])
 # ARG_POSITIONAL_SINGLE([arg-name],[positional argument name])
 # ARG_POSITIONAL_SINGLE([description],[positional argument description])
 # ARG_OPTIONAL_BOOLEAN([empty],[],[value can be empty])
@@ -43,6 +44,7 @@ _arg_short=
 _arg_template=
 _arg_default_value=
 _arg_repeat="off"
+_arg_one_of=()
 _arg_empty="off"
 _arg_empty_value=
 
@@ -50,12 +52,13 @@ _arg_empty_value=
 print_help()
 {
 	printf '%s\n' "<generate the parseArg parseable string for positional argument>"
-	printf 'Usage: %s [-s|--short <arg>] [--template <arg>] [-d|--default-value <arg>] [-r|--(no-)repeat] [--(no-)empty] [--empty-value <arg>] [-h|--help] <arg-name> <description>\n' "$0"
+	printf 'Usage: %s [-s|--short <arg>] [--template <arg>] [-d|--default-value <arg>] [-r|--(no-)repeat] [--one-of <arg>] [--(no-)empty] [--empty-value <arg>] [-h|--help] <arg-name> <description>\n' "$0"
 	printf '\t%s\n' "<arg-name>: positional argument name"
 	printf '\t%s\n' "<description>: positional argument description"
 	printf '\t%s\n' "-s, --short: short option (no default)"
 	printf '\t%s\n' "-d, --default-value: default value (no default)"
 	printf '\t%s\n' "-r, --repeat, --no-repeat: repeatable (off by default)"
+	printf '\t%s\n' "--one-of: list of accepted values (empty by default)"
 	printf '\t%s\n' "--empty, --no-empty: value can be empty (off by default)"
 	printf '\t%s\n' "--empty-value: value when empty, force --empty (no default)"
 	printf '\t%s\n' "-h, --help: Prints help"
@@ -110,6 +113,14 @@ parse_commandline()
 				then
 					{ begins_with_short_option "$_next" && shift && set -- "-r" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
+				;;
+			--one-of)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_one_of+=("$2")
+				shift
+				;;
+			--one-of=*)
+				_arg_one_of+=("${_key##--one-of=}")
 				;;
 			--no-empty|--empty)
 				_arg_empty="on"
@@ -191,6 +202,10 @@ else
 	setOptStr="${setOptStr}=\"\$2\"";
 fi
 
+if [ "${#_arg_one_of[@]}" -gt 0 ]; then
+	setOptStr+="\n\tif [[ \"\${#_one_of_arg_${_arg_arg_name//-/_}[@]}\" -gt 0 ]];then [[ \"\${_one_of_arg_${_arg_arg_name//-/_}[*]}\" =~ \"_arg_${_arg_arg_name//-/_}\" ]] || die \"$_arg_arg_name must be one of: ${_arg_one_of[*]}\";fi";
+fi
+
 if [ "$_arg_empty" == "on" ] || [ "$_arg_empty_value" != "" ]; then
   if [ "$_arg_empty_value" == "" ]; then
     _arg_empty_value="on"
@@ -216,7 +231,14 @@ else
 	setvalstr="=\"\${_key##--${_arg_arg_name}=}\""
 fi
 optParser="${optParser}--${_arg_arg_name}=*)
-	_arg_${_arg_arg_name//-/_}${setvalstr}
+	_arg_${_arg_arg_name//-/_}${setvalstr}";
+
+if [ "${#_arg_one_of[@]}" -gt 0 ]; then
+	optParser+="
+	if [[ \"\${#_one_of_arg_${_arg_arg_name//-/_}[@]}\" -gt 0 ]];then [[ \"\${_one_of_arg_${_arg_arg_name//-/_}[*]}\" =~ \"_arg_${_arg_arg_name//-/_}\" ]] || die \"$_arg_arg_name must be one of: ${_arg_one_of[*]}\";fi";
+fi
+
+optParser+="
 	;;
 ";
 
@@ -227,7 +249,13 @@ if [ "$_arg_short" != "" ]; then
 		setvalsstr="=\"\${_key##-${_arg_short}}\""
 	fi
   optParser="${optParser}-${_arg_short}*)
-	_arg_${_arg_arg_name//-/_}${setvalsstr}
+	_arg_${_arg_arg_name//-/_}${setvalsstr}";
+if [ "${#_arg_one_of[@]}" -gt 0 ]; then
+	optParser+="
+	if [[ \"\${#_one_of_arg_${_arg_arg_name//-/_}[@]}\" -gt 0 ]];then [[ \"\${_one_of_arg_${_arg_arg_name//-/_}[*]}\" =~ \"_arg_${_arg_arg_name//-/_}\" ]] || die \"$_arg_arg_name must be one of: ${_arg_one_of[*]}\";fi";
+fi
+
+optParser+="
 	;;
 ";
 fi
