help for subcmd kinda working

diff --git a/bin/help/parser b/bin/help/parser
--- a/bin/help/parser
+++ b/bin/help/parser
@@ -1,11 +1,12 @@
 #!/bin/bash
 
 # @parseArger-begin
-# @parseArger-help "create help parser"
+# @parseArger-help "create help parser" --option "help" --short-option "h"
 # @parseArger-declarations
 # @parseArger pos message "your main help message"
 # @parseArger opt option "help trigger option" --default-value "help"
 # @parseArger opt short-option "help trigger short option" --default-value "h"
+# @parseArger flag has-subcommand "do not exit after print_help"
 # @parseArger-declarations-end
 
 # @parseArger-parsing
@@ -32,16 +33,20 @@ _arg_message="";
 _arg_option="help"
 _arg_short_option="h"
 # FLAGS
+_arg_has_subcommand="off"
 
 
 print_help()
 {
+
 	echo -e "create help parser:"
 	echo -e "	message: your main help message"
 	echo -e "	--option <option>: help trigger option [default: ' help ']"
 	echo -e "	--short-option <short-option>: help trigger short option [default: ' h ']"
+	echo -e "	--has-subcommand|--no-has-subcommand: do not exit after print_help"
 	echo -e "Usage :
-	$0 <> [--option <value>] [--short-option <value>]"
+	$0 <message> [--option <value>] [--short-option <value>] [--[no-]has-subcommand]";
+
 }
 
 parse_commandline()
@@ -69,6 +74,18 @@ parse_commandline()
 				_arg_short_option="${_key##--short-option=}"
 				;;
 			
+			--no-has-subcommand|--has-subcommand)
+				_arg_has_subcommand="on"
+				test "${1:0:5}" = "--no-" && _arg_has_subcommand="off"
+				;;
+			-h|--help)
+				print_help;
+			
+				;;
+			-h*)
+				print_help;
+			
+				;;
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -82,7 +99,7 @@ parse_commandline()
 
 handle_passed_args_count()
 {
-	local _required_args_string=""
+	local _required_args_string="message"
 	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
 }
@@ -95,7 +112,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
+eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
 		shift;
 	done
 }
@@ -106,15 +124,22 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "\t: ${_arg_message}";
-	echo -e "\tshort-option: ${_arg_option | sed 's/-/_/g'}";
-	echo -e "\t: ${_arg_short-option | sed 's/-/_/g'}";
+	echo -e "\tmessage: ${_arg_message}";
+	echo -e "\toption: ${_arg_option | sed 's/-/_/g'}";
+	echo -e "\tshort-option: ${_arg_short-option | sed 's/-/_/g'}";
+	echo -e "\thas-subcommand: ${_arg_has-subcommand | sed 's/-/_/g'}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
@@ -130,13 +155,17 @@ if [ "$_arg_short_option" != "" ]; then
 fi
 
 echo -e "$outStr)
-	print_help;
-	exit 0;
-	;;";
+	print_help;"
+	if [[ "$_arg_has_subcommand" == "off" ]]; then
+		echo -e "	exit 0;";
+	fi
+	echo -e "	;;";
 
 if [ "$_arg_short_option" != "" ]; then
 	echo -e "-${_arg_short_option}*)
-	print_help;
-	exit 0;
-	;;";
+	print_help;"
+	if [[ "$_arg_has_subcommand" == "off" ]]; then
+		echo -e "	exit 0;";
+	fi
+	echo -e "	;;";
 fi
